/* =====================================================================
 * 菌物志 · 菌菌有神 · 云南野生菌数据库
 * 字段说明：
 *   id          唯一标识
 *   name        中文名
 *   latin       学名
 *   aliases     别名
 *   category    安全性：edible 可食用 | caution 慎食(需彻底加工) | toxic 有毒/剧毒
 *   season      常见出菇季节（字符串，用于展示）
 *   seasons     用于筛选的季节数组：["春","夏","秋"]
 *   habitat     生境（字符串，用于展示）
 *   habitats    用于筛选的生境数组：["林地","草地","腐木"]
 *   features    结构化识别特征（供特征问答筛选使用）
 *   description 识别要点（展示）
 *   caution     食用安全 / 毒性说明（展示）
 *   similar     易混淆种（展示）
 *   svg         插图参数（可选；缺省时由 features 自动派生）
 * ===================================================================== */

window.MUSHROOMS = [
  /* ---------------------------- 可食用 ---------------------------- */
  {
    id: "songrong",
    name: "松茸",
    latin: "Tricholoma matsutake",
    aliases: ["松口蘑", "松蕈"],
    category: "edible",
    season: "7—10 月",
    seasons: ["夏", "秋"],
    habitat: "松林、栎林混交林地",
    habitats: ["林地"],
    features: {
      capColor: "棕褐",
      hymenium: "白色",
      hymeniumType: "菌褶",
      stem: "粗壮、与菌盖同色",
      ring: false,
      volva: false,
      bruise: "不变",
      habitat: "林地",
      seasons: ["夏", "秋"]
    },
    description: "菌盖棕褐色、被纤维状鳞片，幼时半球形后平展；菌褶白色、较密；菌柄粗壮、与菌盖同色；有独特而浓郁的松香气息。",
    caution: "名贵食用菌，肉质细嫩、香气独特。务必与外观相似的菌种区分确认后再食用，并充分加热。",
    similar: ["与部分牛肝菌幼体、鹅膏幼体需注意区分，松茸以独特松香与白色菌褶为显著特征。"],
    svg: { form: "agaric", capShape: "convex", cap: "#9c6b43", cap2: "#7a4f2e", texture: "fibrillose", stem: "#d9b98c", gill: "#f4ead8", bulbous: false }
  },
  {
    id: "jizong",
    name: "鸡枞",
    latin: "Termitomyces spp.",
    aliases: ["鸡肉菌", "鸡枞菌", "白蚁伞"],
    category: "edible",
    season: "6—9 月",
    seasons: ["夏", "秋"],
    habitat: "白蚁巢上方林地",
    habitats: ["林地"],
    features: {
      capColor: "灰褐",
      hymenium: "白色",
      hymeniumType: "菌褶",
      stem: "细长、具明显假根",
      ring: false,
      volva: false,
      bruise: "不变",
      habitat: "林地",
      seasons: ["夏", "秋"]
    },
    description: "菌盖灰褐色、中央尖凸呈斗笠状；菌褶白色；菌柄细长、基部有明显向下延伸的假根（连接白蚁巢）；夏秋雨后常见。",
    caution: "味道极鲜美的著名食用菌。注意与白色或浅色的鹅膏类区分：鸡枞无菌环、无菌托，且具典型假根。",
    similar: ["与部分白色鹅膏（有菌环、菌托，多剧毒）混淆风险高，务必确认无菌环、无菌托。"],
    svg: { form: "agaric", capShape: "conical", cap: "#7d7468", cap2: "#5f574d", texture: "smooth", stem: "#e8e0d0", gill: "#f6f0e4", bulbous: false, pseudorhiza: true }
  },
  {
    id: "ganbajun",
    name: "干巴菌",
    latin: "Thelephora ganbajun",
    aliases: ["干巴革菌", "牛牙齿菌"],
    category: "edible",
    season: "6—9 月",
    seasons: ["夏", "秋"],
    habitat: "松林地面",
    habitats: ["林地"],
    features: {
      capColor: "灰黑",
      hymenium: "无典型菌褶（珊瑚状）",
      hymeniumType: "珊瑚状",
      stem: "短粗、多分枝",
      ring: false,
      volva: false,
      bruise: "不变",
      habitat: "林地",
      seasons: ["夏", "秋"]
    },
    description: "形态特殊：整体莲座状、珊瑚状多分枝，灰黑褐色，质地坚韧；多生于松林下。",
    caution: "云南名贵食用菌，香气浓郁、嚼劲十足。因形态特殊，易与其它革菌类混淆，需有经验者辨识。",
    similar: ["与其它革菌类（Thelephora 属）较难区分，建议仅由有经验者采集。"],
    svg: { form: "coral", cap: "#4a443e", cap2: "#332f2b", stem: "#4a443e", gill: "#4a443e" }
  },
  {
    id: "niuganjun",
    name: "美味牛肝菌",
    latin: "Boletus edulis",
    aliases: ["大脚菇", "白牛肝"],
    category: "edible",
    season: "6—9 月",
    seasons: ["夏", "秋"],
    habitat: "针叶林、阔叶林地",
    habitats: ["林地"],
    features: {
      capColor: "褐",
      hymenium: "初白后黄",
      hymeniumType: "菌管",
      stem: "粗壮、具网纹",
      ring: false,
      volva: false,
      bruise: "不变",
      habitat: "林地",
      seasons: ["夏", "秋"]
    },
    description: "菌盖褐色、半球形；菌盖下为密集菌管（孔口），初白色后转黄绿色；菌柄粗壮、上部常具细网纹。",
    caution: "优质食用菌。注意与味苦的苦粉孢牛肝菌、网柄牛肝菌等区分，并充分煮熟。",
    similar: ["苦粉孢牛肝菌（味极苦）、部分网柄牛肝菌需注意区分。"],
    svg: { form: "bolete", capShape: "convex", cap: "#8b5e34", cap2: "#6f4a29", texture: "smooth", stem: "#dcc8a8", gill: "#e8d08a", bulbous: false }
  },
  {
    id: "jianshouqing",
    name: "见手青",
    latin: "Lanmaoa asiatica 等",
    aliases: ["蓝见手", "红见手", "小美牛肝菌"],
    category: "caution",
    season: "6—9 月",
    seasons: ["夏", "秋"],
    habitat: "松林、栎林地",
    habitats: ["林地"],
    features: {
      capColor: "褐红",
      hymenium: "黄色",
      hymeniumType: "菌管",
      stem: "粗壮",
      ring: false,
      volva: false,
      bruise: "变蓝",
      habitat: "林地",
      seasons: ["夏", "秋"]
    },
    description: "菌盖褐红至黄褐色；菌管黄色；最显著特征是菌肉、菌管受伤后迅速变为蓝绿色，故名「见手青」。",
    caution: "慎食！生食或未彻底煮熟会中毒（胃肠炎 + 神经精神症状，如幻觉）。必须切薄片、高温彻底烹熟，且不宜过量。",
    similar: ["见手青是一类受伤变蓝的牛肝菌统称，不同种毒性差异大，切勿自行分辨采食。"],
    svg: { form: "bolete", capShape: "convex", cap: "#a05a3c", cap2: "#7c4429", texture: "smooth", stem: "#d8c0a0", gill: "#e0b84e", bulbous: false, bruise: true }
  },
  {
    id: "qingtoujun",
    name: "青头菌",
    latin: "Russula virescens",
    aliases: ["变绿红菇", "青冈菌"],
    category: "edible",
    season: "6—9 月",
    seasons: ["夏", "秋"],
    habitat: "松林、阔叶林地",
    habitats: ["林地"],
    features: {
      capColor: "绿",
      hymenium: "白色",
      hymeniumType: "菌褶",
      stem: "白色、圆柱形",
      ring: false,
      volva: false,
      bruise: "不变",
      habitat: "林地",
      seasons: ["夏", "秋"]
    },
    description: "菌盖翠绿色、常龟裂成斑块状；菌褶白色；菌柄白色、圆柱形；夏秋松林下常见。",
    caution: "常见食用菌，味鲜美。需与绿色系的其它红菇/鹅膏区分（青头菌无菌环、无菌托）。",
    similar: ["与部分绿色鹅膏（可有菌环、菌托）区分，青头菌无菌环、无菌托。"],
    svg: { form: "agaric", capShape: "convex", cap: "#6fae7a", cap2: "#4f8a5b", texture: "cracked", stem: "#ece7da", gill: "#f5efe2", bulbous: false }
  },
  {
    id: "naijiangjun",
    name: "奶浆菌",
    latin: "Lactarius volemus",
    aliases: ["多汁乳菇", "乳汁菌"],
    category: "edible",
    season: "6—9 月",
    seasons: ["夏", "秋"],
    habitat: "阔叶林地",
    habitats: ["林地"],
    features: {
      capColor: "橙褐",
      hymenium: "白色至黄",
      hymeniumType: "菌褶",
      stem: "与菌盖同色",
      ring: false,
      volva: false,
      bruise: "出白色乳汁",
      habitat: "林地",
      seasons: ["夏", "秋"]
    },
    description: "菌盖橙褐色、中央微凹；菌褶初白色后转黄；菌肉、菌褶受伤后溢出白色乳汁且不变色，是乳菇类的典型特征。",
    caution: "常见食用菌，宜充分煮熟后食用。",
    similar: ["与其它乳菇（部分辛辣、有毒）需区分，奶浆菌乳汁白色且味温和。"],
    svg: { form: "agaric", capShape: "flat", cap: "#d28a4e", cap2: "#b06e37", texture: "smooth", stem: "#d8b98a", gill: "#f2e2c4", bulbous: false }
  },
  {
    id: "laorentoujun",
    name: "老人头菌",
    latin: "Catathelasma ventricosum",
    aliases: ["梭柄松苞菇", "大胖子菇"],
    category: "edible",
    season: "7—9 月",
    seasons: ["夏", "秋"],
    habitat: "松林地",
    habitats: ["林地"],
    features: {
      capColor: "白",
      hymenium: "白色",
      hymeniumType: "菌褶",
      stem: "具菌环、基部膨大",
      ring: true,
      volva: false,
      bruise: "不变",
      habitat: "林地",
      seasons: ["夏", "秋"]
    },
    description: "菌盖白色至淡褐色、半球形；菌褶白色、延生；菌柄有膜质菌环、基部明显膨大。",
    caution: "可食用，但需彻底煮熟。注意与白色系鹅膏（多有菌托）区分。",
    similar: ["与白色鹅膏类（有菌托，多剧毒）区分：老人头菌无菌托、菌褶延生。"],
    svg: { form: "agaric", capShape: "convex", cap: "#e6dcc8", cap2: "#cbbd9f", texture: "smooth", stem: "#ece4d2", gill: "#f4eee0", bulbous: true, ring: true }
  },
  {
    id: "zhusun",
    name: "竹荪",
    latin: "Phallus indusiatus",
    aliases: ["竹笙", "面纱菌", "竹参"],
    category: "edible",
    season: "6—9 月",
    seasons: ["夏", "秋"],
    habitat: "竹林、腐殖质丰富处",
    habitats: ["林地"],
    features: {
      capColor: "白（菌幕）",
      hymenium: "无典型菌褶",
      hymeniumType: "网状菌裙",
      stem: "白色海绵质",
      ring: false,
      volva: false,
      bruise: "不变",
      habitat: "林地",
      seasons: ["夏", "秋"]
    },
    description: "形态特殊：白色海绵质菌柄，顶端为钟形菌盖（表面有黑绿色孢子黏液），菌盖下悬垂洁白网状菌裙（菌幕）。",
    caution: "名贵食用菌。食用前需去除菌盖与基部的菌托（含黏液、有异味），仅取菌柄与菌裙。",
    similar: ["与黄裙竹荪等有毒/不宜食用的竹荪属近缘种区分。"],
    svg: { form: "veiled", cap: "#f4efe2", cap2: "#6b5b3a", stem: "#f7f2e6", gill: "#f7f2e6" }
  },
  {
    id: "huzhangjun",
    name: "虎掌菌",
    latin: "Sarcodon imbricatus",
    aliases: ["翘鳞肉齿菌", "虎掌菇"],
    category: "edible",
    season: "7—10 月",
    seasons: ["夏", "秋"],
    habitat: "松林、云杉林地",
    habitats: ["林地"],
    features: {
      capColor: "褐",
      hymenium: "齿状菌刺",
      hymeniumType: "齿状菌刺",
      stem: "粗短",
      ring: false,
      volva: false,
      bruise: "不变",
      habitat: "林地",
      seasons: ["夏", "秋"]
    },
    description: "菌盖褐色、被大型翘起的鳞片；菌盖下方为密集下垂的齿状菌刺（而非菌褶）。",
    caution: "食用菌，质地脆嫩。注意与外形相近的肉齿菌属其它种区分。",
    similar: ["与肉齿菌属其它种（部分不可食）区分，需有经验者辨识。"],
    svg: { form: "toothed", capShape: "convex", cap: "#6b5340", cap2: "#4a392c", texture: "scaly", stem: "#7a6248", gill: "#9c8a70", bulbous: false }
  },
  {
    id: "dahonggu",
    name: "大红菇",
    latin: "Russula alutacea",
    aliases: ["红菇", "真红菇"],
    category: "edible",
    season: "6—9 月",
    seasons: ["夏", "秋"],
    habitat: "阔叶林地",
    habitats: ["林地"],
    features: {
      capColor: "红",
      hymenium: "白色至黄",
      hymeniumType: "菌褶",
      stem: "白色",
      ring: false,
      volva: false,
      bruise: "不变",
      habitat: "林地",
      seasons: ["夏", "秋"]
    },
    description: "菌盖鲜红色、平展；菌褶初白色后转黄；菌柄白色。味温和、不辣。",
    caution: "食用菌。与味辛辣的毒红菇区分：毒红菇味极辣、菌褶更白。",
    similar: ["毒红菇（Russula emetica，味极辛辣、有毒）外形极相似，务必区分。"],
    svg: { form: "agaric", capShape: "flat", cap: "#c0392b", cap2: "#96281b", texture: "smooth", stem: "#ece7da", gill: "#f1e6cc", bulbous: false }
  },

  /* ---------------------------- 可食用（新增） ---------------------------- */
  { id: "yangdujun", name: "羊肚菌", latin: "Morchella esculenta", aliases: ["羊肚菜", "羊肚蘑"], category: "edible", season: "3—5 月", seasons: ["春"], habitat: "阔叶林、火烧地", habitats: ["林地"], features: { capColor: "褐", hymenium: "蜂窝状凹坑", hymeniumType: "蜂窝状", stem: "白色、中空", ring: false, volva: false, bruise: "不变", habitat: "林地", seasons: ["春"] }, description: "菌盖近球形至圆锥形，表面布满蜂窝状凹坑，浅褐至深褐色；菌柄白色、中空。", caution: "名贵食用菌，须彻底煮熟。与有毒的鹿花菌类区分：羊肚菌菌盖蜂窝状，鹿花菌菌盖脑状回纹。", similar: ["赭鹿花菌（剧毒，菌盖脑状回纹、非蜂窝状）易与羊肚菌混淆。"], svg: { form: "agaric", capShape: "conical", cap: "#7a5c3d", cap2: "#5e452e", texture: "cracked", stem: "#ece5d5", gill: "#e2d6bf", bulbous: false } },
  { id: "jianyangdu", name: "尖顶羊肚菌", latin: "Morchella conica", aliases: ["圆锥羊肚菌"], category: "edible", season: "3—5 月", seasons: ["春"], habitat: "阔叶林、松林地", habitats: ["林地"], features: { capColor: "褐", hymenium: "蜂窝状凹坑", hymeniumType: "蜂窝状", stem: "白色、中空", ring: false, volva: false, bruise: "不变", habitat: "林地", seasons: ["春"] }, description: "菌盖圆锥形、顶端尖，表面蜂窝状凹坑较规则，深褐色；菌柄白色中空。", caution: "食用菌，须彻底煮熟。与羊肚菌同属，识别要点相似。", similar: ["与鹿花菌类（有毒）区分：蜂窝状而非脑状回纹。"], svg: { form: "agaric", capShape: "conical", cap: "#6e5034", cap2: "#4e3824", texture: "cracked", stem: "#ece5d5", gill: "#e2d6bf", bulbous: false } },
  { id: "jiyoujun", name: "鸡油菌", latin: "Cantharellus cibarius", aliases: ["黄菇", "杏菌", "鸡蛋黄菌"], category: "edible", season: "6—9 月", seasons: ["夏", "秋"], habitat: "阔叶林、针叶林地", habitats: ["林地"], features: { capColor: "黄", hymenium: "黄色、菌褶下延", hymeniumType: "菌褶", stem: "黄色、与菌盖连生", ring: false, volva: false, bruise: "不变", habitat: "林地", seasons: ["夏", "秋"] }, description: "菌盖鲜黄色、漏斗状，边缘波状；菌褶为下延的黄色棱纹；全株杏黄色，有果香。", caution: "名贵食用菌，香气浓郁。与外形相近的蜡伞类区分。", similar: ["与部分黄色蜡伞、丝膜菌区分，鸡油菌菌褶下延且全株黄色。"], svg: { form: "agaric", capShape: "flat", cap: "#e8c84e", cap2: "#c9a43a", texture: "smooth", stem: "#e8c84e", gill: "#f0d878", bulbous: false } },
  { id: "labajun", name: "喇叭菌", latin: "Craterellus lutescens", aliases: ["金黄喇叭菌", "黄喇叭菌"], category: "edible", season: "6—10 月", seasons: ["夏", "秋"], habitat: "针叶林、阔叶林地", habitats: ["林地"], features: { capColor: "黄", hymenium: "下延棱纹", hymeniumType: "菌褶", stem: "中空、下延至基部", ring: false, volva: false, bruise: "不变", habitat: "林地", seasons: ["夏", "秋"] }, description: "菌体喇叭状、中空，菌盖中央深凹呈漏斗形，黄褐色；菌褶为下延的浅棱纹。", caution: "食用菌，宜炒食或做汤。与鸡油菌近缘，注意与相似蜡伞区分。", similar: ["与鸡油菌属近缘种、部分蜡伞区分。"], svg: { form: "agaric", capShape: "flat", cap: "#c9a243", cap2: "#9c7a30", texture: "smooth", stem: "#c9a243", gill: "#e0c468", bulbous: false } },
  { id: "songrujun", name: "松乳菇", latin: "Lactarius deliciosus", aliases: ["谷熟菌", "铜绿菌", "松菌"], category: "edible", season: "6—10 月", seasons: ["夏", "秋"], habitat: "松林地", habitats: ["林地"], features: { capColor: "橙", hymenium: "橙色、伤后变绿", hymeniumType: "菌褶", stem: "橙色、中空", ring: false, volva: false, bruise: "出橙色乳汁", habitat: "林地", seasons: ["夏", "秋"] }, description: "菌盖橙黄色、常有同心环纹，中央凹陷；菌褶橙色、受伤渐变绿色；伤后溢出橙红色乳汁。", caution: "常见食用菌，须彻底煮熟。乳汁橙红色为其典型特征。", similar: ["与其它乳菇区分，松乳菇乳汁橙红色、伤后变绿。"], svg: { form: "agaric", capShape: "flat", cap: "#d98a3e", cap2: "#b06e2e", texture: "smooth", stem: "#d98a3e", gill: "#e0a05c", bulbous: false } },
  { id: "hongzhiru", name: "红汁乳菇", latin: "Lactarius hatsudake", aliases: ["铜绿菌", "红奶浆菌"], category: "edible", season: "6—10 月", seasons: ["夏", "秋"], habitat: "松林地", habitats: ["林地"], features: { capColor: "橙", hymenium: "橙色、伤后变绿", hymeniumType: "菌褶", stem: "橙色、中空", ring: false, volva: false, bruise: "出红色乳汁", habitat: "林地", seasons: ["夏", "秋"] }, description: "菌盖肉粉色至橙褐色，常有同心环；伤后溢出红色乳汁并渐变绿色。", caution: "食用菌，须彻底煮熟。与松乳菇近缘，识别要点相近。", similar: ["与松乳菇、其它乳菇区分。"], svg: { form: "agaric", capShape: "flat", cap: "#d17a4a", cap2: "#a75e34", texture: "smooth", stem: "#d17a4a", gill: "#e0a068", bulbous: false } },
  { id: "caogu", name: "草菇", latin: "Volvariella volvacea", aliases: ["兰花菇", "秆菇"], category: "edible", season: "5—9 月", seasons: ["春", "夏", "秋"], habitat: "稻草堆、腐草上", habitats: ["腐木"], features: { capColor: "灰", hymenium: "白色", hymeniumType: "菌褶", stem: "具菌托", ring: false, volva: true, bruise: "不变", habitat: "腐木", seasons: ["春", "夏", "秋"] }, description: "菌盖灰黑色、卵形后钟形；菌褶白色；菌柄基部有明显菌托。", caution: "常见食用菌。注意与白色鹅膏（有菌环+菌托）区分：草菇无菌环。", similar: ["与白色鹅膏类（剧毒）区分：草菇无菌环、有菌托。"], svg: { form: "agaric", capShape: "bell", cap: "#6b6f72", cap2: "#4a4d50", texture: "smooth", stem: "#ece7da", gill: "#f4efe2", bulbous: false, volva: true } },
  { id: "xianggu", name: "香菇", latin: "Lentinula edodes", aliases: ["冬菇", "花菇", "香蕈"], category: "edible", season: "全年（人工栽培）", seasons: ["春", "夏", "秋"], habitat: "阔叶树腐木", habitats: ["腐木"], features: { capColor: "褐", hymenium: "白色", hymeniumType: "菌褶", stem: "偏生、具鳞片", ring: false, volva: false, bruise: "不变", habitat: "腐木", seasons: ["春", "夏", "秋"] }, description: "菌盖深褐色、被浅色鳞片；菌褶白色；菌柄偏生、纤维质，有香气。", caution: "最常见食用菌之一，须彻底煮熟。野生香菇与部分相似种需区分。", similar: ["与部分相似的小型褐菌区分。"], svg: { form: "agaric", capShape: "convex", cap: "#7a5a3e", cap2: "#5a4030", texture: "fibrillose", stem: "#d9c9ad", gill: "#f4ead8", bulbous: false } },
  { id: "pinggu", name: "平菇", latin: "Pleurotus ostreatus", aliases: ["侧耳", "蚝菇"], category: "edible", season: "全年（人工栽培）", seasons: ["春", "夏", "秋"], habitat: "阔叶树腐木", habitats: ["腐木"], features: { capColor: "灰", hymenium: "白色", hymeniumType: "菌褶", stem: "侧生、短", ring: false, volva: false, bruise: "不变", habitat: "腐木", seasons: ["春", "夏", "秋"] }, description: "菌盖扇形或贝壳状、灰白色至灰褐色，菌褶白色下延，菌柄侧生。", caution: "常见食用菌，须彻底煮熟。野生平菇注意与相似侧耳区分。", similar: ["与其它侧耳属区分。"], svg: { form: "agaric", capShape: "flat", cap: "#9aa0a3", cap2: "#75797c", texture: "smooth", stem: "#ddd8cc", gill: "#f2ecdc", bulbous: false } },
  { id: "xingbaogu", name: "杏鲍菇", latin: "Pleurotus eryngii", aliases: ["刺芹侧耳", "干贝菇"], category: "edible", season: "全年（人工栽培）", seasons: ["春", "夏", "秋"], habitat: "腐木、栽培料", habitats: ["腐木"], features: { capColor: "白", hymenium: "白色", hymeniumType: "菌褶", stem: "粗壮、肉质", ring: false, volva: false, bruise: "不变", habitat: "腐木", seasons: ["春", "夏", "秋"] }, description: "菌盖浅褐色至白色、半球形；菌柄极粗壮、肉质，是其主要食用部位。", caution: "常见食用菌，须彻底煮熟。", similar: ["人工栽培常见，识别相对容易。"], svg: { form: "agaric", capShape: "convex", cap: "#d8cfbc", cap2: "#b8ad97", texture: "smooth", stem: "#eee7d8", gill: "#f4efe2", bulbous: false } },
  { id: "jinzhengu", name: "金针菇", latin: "Flammulina velutipes", aliases: ["冬菇", "毛柄金钱菌"], category: "edible", season: "秋冬（野生）/ 全年（栽培）", seasons: ["春", "夏", "秋"], habitat: "阔叶树腐木", habitats: ["腐木"], features: { capColor: "黄", hymenium: "白色", hymeniumType: "菌褶", stem: "细长、基部有绒毛", ring: false, volva: false, bruise: "不变", habitat: "腐木", seasons: ["春", "夏", "秋"] }, description: "菌盖黄色、光滑；菌柄细长、深褐色至黑色、基部有绒毛。野生者菌盖色深。", caution: "食用菌，须彻底煮熟。野外与部分相似小型菌注意区分。", similar: ["与相似的小型黄色菌区分。"], svg: { form: "agaric", capShape: "convex", cap: "#d8b54e", cap2: "#b08a30", texture: "smooth", stem: "#c9a86a", gill: "#f4ead8", bulbous: false } },
  { id: "chashugu", name: "茶树菇", latin: "Cyclocybe aegerita", aliases: ["茶薪菇", "杨树菇"], category: "edible", season: "全年（人工栽培）", seasons: ["春", "夏", "秋"], habitat: "阔叶树腐木", habitats: ["腐木"], features: { capColor: "褐", hymenium: "白色", hymeniumType: "菌褶", stem: "具菌环", ring: true, volva: false, bruise: "不变", habitat: "腐木", seasons: ["春", "夏", "秋"] }, description: "菌盖褐色、半球形；菌褶白色；菌柄有菌环，肉质脆嫩。", caution: "食用菌，须彻底煮熟。与相似具环菌类区分。", similar: ["与部分具菌环的食用/毒菌区分。"], svg: { form: "agaric", capShape: "convex", cap: "#8a6240", cap2: "#68482c", texture: "smooth", stem: "#e0d2bc", gill: "#f2e8d4", bulbous: false, ring: true } },
  { id: "huazigu", name: "滑菇", latin: "Pholiota nameko", aliases: ["滑子菇", "珍珠菇"], category: "edible", season: "秋冬（野生）/ 全年（栽培）", seasons: ["春", "夏", "秋"], habitat: "阔叶树腐木", habitats: ["腐木"], features: { capColor: "黄褐", hymenium: "白色", hymeniumType: "菌褶", stem: "具菌环", ring: true, volva: false, bruise: "不变", habitat: "腐木", seasons: ["春", "夏", "秋"] }, description: "菌盖黄褐色、半球形，表面被黏液、极光滑；菌褶白色；菌柄有菌环。", caution: "食用菌，须彻底煮熟。菌盖黏液是其显著特征。", similar: ["与相似具环菌类区分。"], svg: { form: "agaric", capShape: "convex", cap: "#c9963e", cap2: "#9c7026", texture: "smooth", stem: "#e0d2bc", gill: "#f2e8d4", bulbous: false, ring: true } },
  { id: "haixiangu", name: "海鲜菇", latin: "Hypsizygus marmoreus", aliases: ["真姬菇", "蟹味菇", "白玉菇"], category: "edible", season: "全年（人工栽培）", seasons: ["春", "夏", "秋"], habitat: "阔叶树腐木", habitats: ["腐木"], features: { capColor: "白", hymenium: "白色", hymeniumType: "菌褶", stem: "白色、中生", ring: false, volva: false, bruise: "不变", habitat: "腐木", seasons: ["春", "夏", "秋"] }, description: "菌盖白色至浅褐色、半球形；菌褶白色；菌柄白色、中生，常丛生。", caution: "食用菌，须彻底煮熟。", similar: ["与其它白色栽培菇类区分。"], svg: { form: "agaric", capShape: "convex", cap: "#e8e2d4", cap2: "#c9c0ad", texture: "smooth", stem: "#efe9dc", gill: "#f6f1e4", bulbous: false } },
  { id: "houtougu", name: "猴头菇", latin: "Hericium erinaceus", aliases: ["猴头菌", "刺猬菌"], category: "edible", season: "7—10 月", seasons: ["夏", "秋"], habitat: "阔叶树腐木、活树伤口", habitats: ["腐木"], features: { capColor: "白", hymenium: "下垂的针状菌刺", hymeniumType: "齿状菌刺", stem: "无柄、贴生", ring: false, volva: false, bruise: "不变", habitat: "腐木", seasons: ["夏", "秋"] }, description: "子实体球形、无柄，表面密生下垂的长菌刺，白色至淡黄色，形似猴头。", caution: "名贵食用菌兼药用菌，须彻底煮熟。形态独特，易辨认。", similar: ["与其它猴头属（珊瑚状菌刺）近缘种区分。"], svg: { form: "toothed", capShape: "convex", cap: "#f2ede0", cap2: "#d8d0bd", texture: "smooth", stem: "#f2ede0", gill: "#efe8d8", bulbous: false } },
  { id: "heimuer", name: "黑木耳", latin: "Auricularia auricula-judae", aliases: ["木耳", "云耳"], category: "edible", season: "6—9 月（野生）/ 全年（栽培）", seasons: ["春", "夏", "秋"], habitat: "阔叶树腐木", habitats: ["腐木"], features: { capColor: "黑", hymenium: "无典型菌褶（胶质）", hymeniumType: "胶质", stem: "无柄", ring: false, volva: false, bruise: "不变", habitat: "腐木", seasons: ["春", "夏", "秋"] }, description: "子实体耳状、胶质，黑褐色，半透明，干后皱缩、遇水复展。", caution: "常见食用菌，泡发后彻底加热。野外勿与其它胶质菌混淆。", similar: ["与毛木耳、其它胶质菌区分。"], svg: { form: "agaric", capShape: "flat", cap: "#3a3a38", cap2: "#232322", texture: "smooth", stem: "#3a3a38", gill: "#2c2c2a", bulbous: false } },
  { id: "yiner", name: "银耳", latin: "Tremella fuciformis", aliases: ["白木耳", "雪耳"], category: "edible", season: "6—9 月（野生）/ 全年（栽培）", seasons: ["春", "夏", "秋"], habitat: "阔叶树腐木", habitats: ["腐木"], features: { capColor: "白", hymenium: "无典型菌褶（胶质）", hymeniumType: "胶质", stem: "无柄", ring: false, volva: false, bruise: "不变", habitat: "腐木", seasons: ["春", "夏", "秋"] }, description: "子实体由众多白色半透明的瓣片组成，似盛开的菊花，胶质柔软。", caution: "常见食用菌，泡发后彻底加热。与金耳等胶质菌区分。", similar: ["与金耳（金黄色）等胶质菌区分。"], svg: { form: "agaric", capShape: "flat", cap: "#f6f2e8", cap2: "#e0dac9", texture: "smooth", stem: "#f6f2e8", gill: "#efe9d8", bulbous: false } },
  { id: "jiner", name: "金耳", latin: "Naematelia aurantialba", aliases: ["黄木耳", "黄金银耳"], category: "edible", season: "7—10 月", seasons: ["夏", "秋"], habitat: "阔叶树腐木", habitats: ["腐木"], features: { capColor: "黄", hymenium: "无典型菌褶（胶质）", hymeniumType: "胶质", stem: "无柄", ring: false, volva: false, bruise: "不变", habitat: "腐木", seasons: ["夏", "秋"] }, description: "子实体金黄色、脑状或花瓣状，胶质柔软。", caution: "食用菌，泡发后彻底加热。与银耳（白色）区分。", similar: ["与银耳、其它胶质菌区分。"], svg: { form: "agaric", capShape: "flat", cap: "#e0b04e", cap2: "#b88730", texture: "smooth", stem: "#e0b04e", gill: "#d8a844", bulbous: false } },
  { id: "huishuhua", name: "灰树花", latin: "Grifola frondosa", aliases: ["栗蘑", "舞茸", "莲花菌"], category: "edible", season: "8—10 月", seasons: ["夏", "秋"], habitat: "阔叶树根部", habitats: ["林地"], features: { capColor: "灰褐", hymenium: "白色", hymeniumType: "菌管", stem: "多分枝、汇成块状", ring: false, volva: false, bruise: "不变", habitat: "林地", seasons: ["夏", "秋"] }, description: "子实体大型、覆瓦状多分枝，由众多灰褐色扇形菌盖组成莲花状；菌盖下为菌管。", caution: "食用兼药用菌，须彻底煮熟。", similar: ["与珊瑚菌类、其它多孔菌区分。"], svg: { form: "coral", cap: "#8a7a68", cap2: "#615544", stem: "#8a7a68", gill: "#8a7a68" } },
  { id: "saobajun", name: "扫把菌", latin: "Ramaria botrytis", aliases: ["珊瑚菌", "刷把菌", "鸡爪菌"], category: "edible", season: "7—10 月", seasons: ["夏", "秋"], habitat: "阔叶林、针叶林地", habitats: ["林地"], features: { capColor: "黄褐", hymenium: "无典型菌褶（珊瑚状）", hymeniumType: "珊瑚状", stem: "多分枝、珊瑚状", ring: false, volva: false, bruise: "不变", habitat: "林地", seasons: ["夏", "秋"] }, description: "子实体珊瑚状多分枝，浅黄褐至粉紫色，枝端钝圆。", caution: "可食用的珊瑚菌类。注意与部分有毒珊瑚菌（如部分变黑的种）区分，须彻底煮熟。", similar: ["与有毒珊瑚菌类区分，需有经验者辨识。"], svg: { form: "coral", cap: "#c9a06a", cap2: "#9c7a4c", stem: "#c9a06a", gill: "#c9a06a" } },
  { id: "heiniugan", name: "黑牛肝菌", latin: "Boletus aereus", aliases: ["铜色牛肝菌", "黑大脚"], category: "edible", season: "6—9 月", seasons: ["夏", "秋"], habitat: "阔叶林地", habitats: ["林地"], features: { capColor: "黑褐", hymenium: "白色后黄", hymeniumType: "菌管", stem: "粗壮、具网纹", ring: false, volva: false, bruise: "不变", habitat: "林地", seasons: ["夏", "秋"] }, description: "菌盖黑褐色至铜褐色、半球形；菌管初白色后黄；菌柄粗壮、具网纹。", caution: "优质食用菌，须彻底煮熟。与其它深色牛肝菌区分。", similar: ["与其它深色牛肝菌区分。"], svg: { form: "bolete", capShape: "convex", cap: "#4a3a2c", cap2: "#32271e", texture: "smooth", stem: "#c8b090", gill: "#e0d088", bulbous: false } },
  { id: "wangbingniu", name: "网柄牛肝菌", latin: "Boletus reticulatus", aliases: ["网纹牛肝菌", "白葱菌"], category: "edible", season: "6—9 月", seasons: ["夏", "秋"], habitat: "阔叶林地", habitats: ["林地"], features: { capColor: "褐", hymenium: "白色后黄", hymeniumType: "菌管", stem: "粗壮、全柄网纹", ring: false, volva: false, bruise: "不变", habitat: "林地", seasons: ["夏", "秋"] }, description: "菌盖褐色、半球形，常有细裂纹；菌管白色后转黄；菌柄几乎全部具明显网纹。", caution: "食用菌，须彻底煮熟。与美味牛肝菌近缘，识别要点相近。", similar: ["与美味牛肝菌、其它网纹牛肝菌区分。"], svg: { form: "bolete", capShape: "convex", cap: "#8a6a44", cap2: "#684f30", texture: "cracked", stem: "#dcc8a8", gill: "#e8d08a", bulbous: false } },
  { id: "huangniugan", name: "黄牛肝菌", latin: "Suillus luteus", aliases: ["褐环乳牛肝菌", "滑肚子", "黄粘团子"], category: "edible", season: "6—9 月", seasons: ["夏", "秋"], habitat: "松林地", habitats: ["林地"], features: { capColor: "黄褐", hymenium: "黄色", hymeniumType: "菌管", stem: "具菌环", ring: true, volva: false, bruise: "不变", habitat: "林地", seasons: ["夏", "秋"] }, description: "菌盖黄褐色、粘滑；菌管黄色；菌柄有菌环。", caution: "可食用，但菌盖黏液易致部分人肠胃不适，建议去皮并彻底煮熟。", similar: ["与其它乳牛肝菌（Suillus）区分。"], svg: { form: "bolete", capShape: "convex", cap: "#b88a4a", cap2: "#8c6634", texture: "smooth", stem: "#dcc8a0", gill: "#e0c060", bulbous: false, ring: true } },
  { id: "songtaniu", name: "松塔牛肝菌", latin: "Strobilomyces strobilaceus", aliases: ["黑麻蛇菌", "松塔菇"], category: "edible", season: "6—9 月", seasons: ["夏", "秋"], habitat: "阔叶林地", habitats: ["林地"], features: { capColor: "黑褐", hymenium: "灰白后黑", hymeniumType: "菌管", stem: "具鳞片", ring: false, volva: false, bruise: "变红至黑", habitat: "林地", seasons: ["夏", "秋"] }, description: "菌盖黑褐色、被大型翘起的鳞片；菌管灰白，伤后变红再变黑；菌柄亦被鳞片。", caution: "可食用，须彻底煮熟。与相似深色鳞片菌区分。", similar: ["与虎掌菌、其它鳞片菌区分。"], svg: { form: "bolete", capShape: "convex", cap: "#4a3a30", cap2: "#32261f", texture: "scaly", stem: "#5a463a", gill: "#9a8a7a", bulbous: false } },
  { id: "jizonghua", name: "鸡枞花", latin: "Termitomyces microcarpus", aliases: ["小鸡枞", "斗篷鸡枞"], category: "edible", season: "6—9 月", seasons: ["夏", "秋"], habitat: "白蚁巢上方林地", habitats: ["林地"], features: { capColor: "白", hymenium: "白色", hymeniumType: "菌褶", stem: "细长、具假根", ring: false, volva: false, bruise: "不变", habitat: "林地", seasons: ["夏", "秋"] }, description: "体型较小的鸡枞类，菌盖白色、中央尖凸；菌褶白色；菌柄细长、具假根，常群生。", caution: "食用菌，味鲜美。识别要点同鸡枞：无菌环、无菌托、具假根。", similar: ["与白色鹅膏（剧毒）区分：鸡枞花无菌环、菌托。"], svg: { form: "agaric", capShape: "conical", cap: "#e8e2d2", cap2: "#c9c0ad", texture: "smooth", stem: "#eee8da", gill: "#f6f1e4", bulbous: false, pseudorhiza: true } },
  { id: "heisonglu", name: "黑松露", latin: "Tuber indicum", aliases: ["块菌", "猪拱菌", "黑块菌"], category: "edible", season: "11—2 月", seasons: ["秋"], habitat: "松栎林地下", habitats: ["林地"], features: { capColor: "黑", hymenium: "无典型菌褶（块菌）", hymeniumType: "块菌", stem: "无柄、块状", ring: false, volva: false, bruise: "不变", habitat: "林地", seasons: ["秋"] }, description: "子实体为地下块状菌，黑褐色、表面多疣状突起，切面具大理石状纹路，香气独特。", caution: "名贵食用菌。与外形相似的假松露（部分有毒）需有经验者区分。", similar: ["与其它地下块菌、硬皮马勃类（有毒）区分。"], svg: { form: "agaric", capShape: "convex", cap: "#3a332c", cap2: "#211d18", texture: "cracked", stem: "#3a332c", gill: "#2c2620", bulbous: false } },
  { id: "lingzhi", name: "灵芝", latin: "Ganoderma lucidum", aliases: ["赤芝", "仙草", "瑞草"], category: "edible", season: "6—9 月", seasons: ["夏", "秋"], habitat: "阔叶树腐木、树桩", habitats: ["腐木"], features: { capColor: "红褐", hymenium: "白色菌孔", hymeniumType: "菌管", stem: "侧生、有光泽", ring: false, volva: false, bruise: "不变", habitat: "腐木", seasons: ["夏", "秋"] }, description: "子实体肾形、木栓质，菌盖红褐色、有漆样光泽和同心环纹；菌盖下为白色菌孔。", caution: "药用菌，多作保健品而非日常蔬菜，不直接生食。", similar: ["与其它灵芝属、树舌（Ganoderma applanatum）区分。"], svg: { form: "bolete", capShape: "flat", cap: "#8a4a30", cap2: "#5c2f1e", texture: "smooth", stem: "#8a4a30", gill: "#d8c8a8", bulbous: false } },
  { id: "tonglujun", name: "铜绿菌", latin: "Russula aeruginea", aliases: ["铜绿红菇", "青头菌近缘种"], category: "edible", season: "6—9 月", seasons: ["夏", "秋"], habitat: "松林、阔叶林地", habitats: ["林地"], features: { capColor: "绿", hymenium: "白色", hymeniumType: "菌褶", stem: "白色", ring: false, volva: false, bruise: "不变", habitat: "林地", seasons: ["夏", "秋"] }, description: "菌盖铜绿色至灰绿色、半球形后平展；菌褶白色；菌柄白色。", caution: "食用菌，须彻底煮熟。与绿色系红菇/鹅膏区分（无菌环、无菌托）。", similar: ["与青头菌、其它绿色红菇区分。"], svg: { form: "agaric", capShape: "convex", cap: "#6f9a78", cap2: "#4f7a58", texture: "smooth", stem: "#ece7da", gill: "#f5efe2", bulbous: false } },
  { id: "zhenmo", name: "榛蘑", latin: "Armillaria mellea", aliases: ["蜜环菌", "栎蘑"], category: "edible", season: "7—9 月", seasons: ["夏", "秋"], habitat: "阔叶树腐木、根部", habitats: ["腐木"], features: { capColor: "黄褐", hymenium: "白色", hymeniumType: "菌褶", stem: "具菌环", ring: true, volva: false, bruise: "不变", habitat: "腐木", seasons: ["夏", "秋"] }, description: "菌盖黄褐色、被细鳞片；菌褶白色；菌柄有菌环，常群生于树根/腐木。", caution: "食用菌，须彻底煮熟。与相似的具环菌类区分。", similar: ["与部分具菌环的毒菌区分。"], svg: { form: "agaric", capShape: "convex", cap: "#b08a4e", cap2: "#826234", texture: "fibrillose", stem: "#dcc8a0", gill: "#f2e8d4", bulbous: false, ring: true } },
  { id: "fengweigu", name: "凤尾菇", latin: "Pleurotus sajor-caju", aliases: ["印度平菇", "环柄侧耳"], category: "edible", season: "全年（人工栽培）", seasons: ["春", "夏", "秋"], habitat: "腐木、栽培料", habitats: ["腐木"], features: { capColor: "灰褐", hymenium: "白色", hymeniumType: "菌褶", stem: "侧生、短", ring: false, volva: false, bruise: "不变", habitat: "腐木", seasons: ["春", "夏", "秋"] }, description: "菌盖扇形、灰褐色，菌褶白色下延，菌柄侧生。", caution: "常见食用菌，须彻底煮熟。", similar: ["与平菇等侧耳类区分。"], svg: { form: "agaric", capShape: "flat", cap: "#9a8a76", cap2: "#756857", texture: "smooth", stem: "#ddd8cc", gill: "#f2ecdc", bulbous: false } },
  { id: "bailinggu", name: "白灵菇", latin: "Pleurotus nebrodensis", aliases: ["阿魏侧耳", "白灵侧耳"], category: "edible", season: "全年（人工栽培）", seasons: ["春", "夏", "秋"], habitat: "腐木、栽培料", habitats: ["腐木"], features: { capColor: "白", hymenium: "白色", hymeniumType: "菌褶", stem: "侧生、粗壮", ring: false, volva: false, bruise: "不变", habitat: "腐木", seasons: ["春", "夏", "秋"] }, description: "菌盖白色、扇形至近圆形，菌褶白色下延，菌柄粗壮、侧生。", caution: "食用菌，须彻底煮熟。", similar: ["与杏鲍菇等白色侧耳区分。"], svg: { form: "agaric", capShape: "flat", cap: "#efe9dc", cap2: "#d4ccb8", texture: "smooth", stem: "#efe9dc", gill: "#f6f1e4", bulbous: false } },
  { id: "jisongrong", name: "姬松茸", latin: "Agaricus subrufescens", aliases: ["巴西蘑菇", "小松菇"], category: "edible", season: "全年（人工栽培）", seasons: ["春", "夏", "秋"], habitat: "栽培料", habitats: ["腐木"], features: { capColor: "褐", hymenium: "初白后褐", hymeniumType: "菌褶", stem: "具菌环", ring: true, volva: false, bruise: "不变", habitat: "腐木", seasons: ["春", "夏", "秋"] }, description: "菌盖褐色、半球形，被纤维状鳞片；菌褶初白色后转褐色；菌柄有菌环。", caution: "食用菌，须彻底煮熟。注意与野生蘑菇属区分。", similar: ["与蘑菇属（Agaricus）其它种区分。"], svg: { form: "agaric", capShape: "convex", cap: "#9c7448", cap2: "#74542f", texture: "fibrillose", stem: "#e2d4bc", gill: "#c9a888", bulbous: false, ring: true } },
  { id: "shuangbaogu", name: "双孢蘑菇", latin: "Agaricus bisporus", aliases: ["口蘑", "白蘑菇", "洋菇"], category: "edible", season: "全年（人工栽培）", seasons: ["春", "夏", "秋"], habitat: "栽培料", habitats: ["腐木"], features: { capColor: "白", hymenium: "初粉后褐", hymeniumType: "菌褶", stem: "具菌环", ring: true, volva: false, bruise: "不变", habitat: "腐木", seasons: ["春", "夏", "秋"] }, description: "菌盖白色至浅褐色、半球形；菌褶初粉红色后转深褐色；菌柄有菌环。", caution: "最常见食用菌，须彻底煮熟。野生白蘑菇务必与白色鹅膏（剧毒）区分。", similar: ["与白色鹅膏类（剧毒，有菌托）区分：双孢蘑菇无菌托、菌褶后转褐色。"], svg: { form: "agaric", capShape: "convex", cap: "#f0eadc", cap2: "#d4ccb8", texture: "smooth", stem: "#efe9dc", gill: "#b08a78", bulbous: false, ring: true } },
  { id: "daqiugaigu", name: "大球盖菇", latin: "Stropharia rugosoannulata", aliases: ["皱环球盖菇", "酒红球盖菇"], category: "edible", season: "4—6 月（野生）/ 全年（栽培）", seasons: ["春", "夏", "秋"], habitat: "草地、秸秆堆", habitats: ["草地", "腐木"], features: { capColor: "红褐", hymenium: "灰紫后黑", hymeniumType: "菌褶", stem: "具菌环", ring: true, volva: false, bruise: "不变", habitat: "草地", seasons: ["春", "夏", "秋"] }, description: "菌盖酒红褐色、半球形；菌褶初灰紫色后转黑；菌柄粗壮、有菌环。", caution: "食用菌，须彻底煮熟。与部分相似具环菌类区分。", similar: ["与球盖菇属其它种区分。"], svg: { form: "agaric", capShape: "convex", cap: "#9c5a44", cap2: "#74422f", texture: "smooth", stem: "#e0d2bc", gill: "#8a7a90", bulbous: false, ring: true } },
  { id: "zilamo", name: "紫蜡蘑", latin: "Laccaria amethystina", aliases: ["紫晶蜡蘑", "紫蘑菇"], category: "edible", season: "6—9 月", seasons: ["夏", "秋"], habitat: "阔叶林、混交林地", habitats: ["林地"], features: { capColor: "紫", hymenium: "紫色", hymeniumType: "菌褶", stem: "紫色", ring: false, volva: false, bruise: "不变", habitat: "林地", seasons: ["夏", "秋"] }, description: "全株紫色：菌盖紫色、菌褶紫色稀疏、菌柄紫色，小型。", caution: "可食用，但颜色易与部分丝膜菌（含毒）混淆，须有经验者辨识并彻底煮熟。", similar: ["与紫色丝膜菌（部分有毒）区分。"], svg: { form: "agaric", capShape: "convex", cap: "#8a6fa8", cap2: "#685180", texture: "smooth", stem: "#8a6fa8", gill: "#a08cc0", bulbous: false } },
  { id: "xiuzhengu", name: "秀珍菇", latin: "Pleurotus pulmonarius", aliases: ["肺形侧耳", "袖珍菇"], category: "edible", season: "全年（人工栽培）", seasons: ["春", "夏", "秋"], habitat: "腐木、栽培料", habitats: ["腐木"], features: { capColor: "灰白", hymenium: "白色", hymeniumType: "菌褶", stem: "侧生", ring: false, volva: false, bruise: "不变", habitat: "腐木", seasons: ["春", "夏", "秋"] }, description: "菌盖灰白色至浅褐色、扇形，菌褶白色下延，菌柄侧生，常丛生。", caution: "食用菌，须彻底煮熟。", similar: ["与平菇等侧耳类区分。"], svg: { form: "agaric", capShape: "flat", cap: "#c4c0b4", cap2: "#9a968a", texture: "smooth", stem: "#ddd8cc", gill: "#f2ecdc", bulbous: false } },
  { id: "yuhuangmo", name: "榆黄蘑", latin: "Pleurotus citrinopileatus", aliases: ["金顶侧耳", "黄平菇"], category: "edible", season: "6—9 月（野生）/ 全年（栽培）", seasons: ["春", "夏", "秋"], habitat: "榆树等腐木", habitats: ["腐木"], features: { capColor: "黄", hymenium: "白色", hymeniumType: "菌褶", stem: "侧生", ring: false, volva: false, bruise: "不变", habitat: "腐木", seasons: ["春", "夏", "秋"] }, description: "菌盖鲜黄色、漏斗状，菌褶白色下延，菌柄侧生。", caution: "食用菌，须彻底煮熟。", similar: ["与其它黄色侧耳区分。"], svg: { form: "agaric", capShape: "flat", cap: "#e0c04e", cap2: "#b89830", texture: "smooth", stem: "#ddd8cc", gill: "#f2ecdc", bulbous: false } },
  { id: "maodinggu", name: "铆钉菇", latin: "Chroogomphus rutilus", aliases: ["血红铆钉菇", "松伞菌"], category: "edible", season: "7—9 月", seasons: ["夏", "秋"], habitat: "松林地", habitats: ["林地"], features: { capColor: "红褐", hymenium: "下延菌褶", hymeniumType: "菌褶", stem: "与菌盖同色", ring: false, volva: false, bruise: "不变", habitat: "林地", seasons: ["夏", "秋"] }, description: "菌盖红褐色、钟形后平展，中央突起；菌褶下延、灰褐带紫；菌柄与菌盖同色。", caution: "食用菌，须彻底煮熟。与丝膜菌类区分。", similar: ["与红褐色的丝膜菌（部分有毒）区分。"], svg: { form: "agaric", capShape: "conical", cap: "#9c5a3e", cap2: "#74422c", texture: "smooth", stem: "#9c5a3e", gill: "#8a7a86", bulbous: false } },
  { id: "huangsan", name: "黄伞", latin: "Pholiota adiposa", aliases: ["黄柳菇", "肥鳞伞"], category: "edible", season: "8—10 月", seasons: ["夏", "秋"], habitat: "阔叶树腐木", habitats: ["腐木"], features: { capColor: "黄", hymenium: "白色", hymeniumType: "菌褶", stem: "具菌环", ring: true, volva: false, bruise: "不变", habitat: "腐木", seasons: ["夏", "秋"] }, description: "菌盖黄色、被褐色鳞片，粘滑；菌褶白色；菌柄有菌环。", caution: "食用菌，须彻底煮熟。与相似鳞伞属（部分有毒）区分。", similar: ["与鳞伞属其它种区分。"], svg: { form: "agaric", capShape: "convex", cap: "#d8b04e", cap2: "#a88430", texture: "scaly", stem: "#dcc8a0", gill: "#f2e8d4", bulbous: false, ring: true } },
  { id: "yuer", name: "榆耳", latin: "Gloeostereum incarnatum", aliases: ["胶韧革菌", "榆蘑"], category: "edible", season: "6—9 月", seasons: ["夏", "秋"], habitat: "榆树腐木", habitats: ["腐木"], features: { capColor: "粉褐", hymenium: "无典型菌褶（胶质）", hymeniumType: "胶质", stem: "无柄", ring: false, volva: false, bruise: "不变", habitat: "腐木", seasons: ["夏", "秋"] }, description: "子实体胶质、粉褐至肉色，扇形或耳状，无柄、贴生。", caution: "食用菌，泡发后彻底加热。与其它胶质菌区分。", similar: ["与木耳、其它胶质菌区分。"], svg: { form: "agaric", capShape: "flat", cap: "#c99a8a", cap2: "#9c7266", texture: "smooth", stem: "#c99a8a", gill: "#b88878", bulbous: false } },
  { id: "touzhuangmabo", name: "头状秃马勃", latin: "Calvatia craniiformis", aliases: ["马勃", "灰包"], category: "edible", season: "7—9 月", seasons: ["夏", "秋"], habitat: "林地、草地", habitats: ["林地", "草地"], features: { capColor: "白", hymenium: "无典型菌褶（包被）", hymeniumType: "马勃", stem: "无柄、块状", ring: false, volva: false, bruise: "不变", habitat: "林地", seasons: ["夏", "秋"] }, description: "子实体头状、白色至淡褐，内部幼时白色；成熟后内部变黄褐色、破裂散出孢子粉。", caution: "仅幼嫩（内部纯白）时可食，须彻底煮熟；成熟/变色者不可食，且易与有毒马勃混淆。", similar: ["与橙黄硬皮马勃等（有毒）区分：有毒马勃内部常带色/硬。"], svg: { form: "agaric", capShape: "convex", cap: "#efe9dc", cap2: "#d4ccb8", texture: "smooth", stem: "#efe9dc", gill: "#e2d8c4", bulbous: false } },
  { id: "changgenjun", name: "长根菇", latin: "Oudemansiella radicata", aliases: ["长根小奥德蘑", "露水鸡枞"], category: "edible", season: "6—9 月", seasons: ["夏", "秋"], habitat: "阔叶林地", habitats: ["林地"], features: { capColor: "褐", hymenium: "白色", hymeniumType: "菌褶", stem: "细长、具长根", ring: false, volva: false, bruise: "不变", habitat: "林地", seasons: ["夏", "秋"] }, description: "菌盖褐色、平展，中央微凸；菌褶白色；菌柄细长、基部延伸成假根状。", caution: "食用菌，须彻底煮熟。与鸡枞类形态略似，注意区分。", similar: ["与鸡枞类区分。"], svg: { form: "agaric", capShape: "flat", cap: "#8a6a4a", cap2: "#684e34", texture: "smooth", stem: "#e0d2bc", gill: "#f4ead8", bulbous: false, pseudorhiza: true } },
  { id: "heilabajun", name: "黑喇叭菌", latin: "Craterellus cornucopioides", aliases: ["灰喇叭菌", "喇叭菇"], category: "edible", season: "7—10 月", seasons: ["夏", "秋"], habitat: "阔叶林地", habitats: ["林地"], features: { capColor: "灰黑", hymenium: "光滑、下延", hymeniumType: "菌褶", stem: "中空、喇叭状", ring: false, volva: false, bruise: "不变", habitat: "林地", seasons: ["夏", "秋"] }, description: "子实体喇叭状、中空，灰黑至黑褐色，菌盖边缘波状，全株向下渐细。", caution: "食用菌，香气浓郁。与鸡油菌类近缘。", similar: ["与喇叭菌属其它种区分。"], svg: { form: "agaric", capShape: "flat", cap: "#3a3a38", cap2: "#232322", texture: "smooth", stem: "#3a3a38", gill: "#4a4a46", bulbous: false } },
  { id: "maomuer", name: "毛木耳", latin: "Auricularia polytricha", aliases: ["粗木耳", "黄背木耳"], category: "edible", season: "6—9 月（野生）/ 全年（栽培）", seasons: ["春", "夏", "秋"], habitat: "阔叶树腐木", habitats: ["腐木"], features: { capColor: "黑褐", hymenium: "无典型菌褶（胶质）", hymeniumType: "胶质", stem: "无柄", ring: false, volva: false, bruise: "不变", habitat: "腐木", seasons: ["春", "夏", "秋"] }, description: "子实体耳状、胶质，背面密生灰白色绒毛，腹面黑褐色。", caution: "食用菌，泡发后彻底加热。与黑木耳（背面光滑）区分。", similar: ["与黑木耳区分：毛木耳背面有绒毛。"], svg: { form: "agaric", capShape: "flat", cap: "#3a3a38", cap2: "#232322", texture: "fibrillose", stem: "#3a3a38", gill: "#2c2c2a", bulbous: false } },
  { id: "heimaiyangdu", name: "黑脉羊肚菌", latin: "Morchella angusticeps", aliases: ["黑羊肚菌", "小顶羊肚菌"], category: "edible", season: "3—5 月", seasons: ["春"], habitat: "松林、火烧地", habitats: ["林地"], features: { capColor: "黑褐", hymenium: "蜂窝状凹坑", hymeniumType: "蜂窝状", stem: "白色、中空", ring: false, volva: false, bruise: "不变", habitat: "林地", seasons: ["春"] }, description: "菌盖圆锥形、黑褐色，蜂窝状凹坑的纵棱较深；菌柄白色中空。", caution: "食用菌，须彻底煮熟。与鹿花菌类（有毒）区分。", similar: ["与赭鹿花菌（剧毒）区分。"], svg: { form: "agaric", capShape: "conical", cap: "#4a3a30", cap2: "#32261f", texture: "cracked", stem: "#ece5d5", gill: "#e2d6bf", bulbous: false } },
  { id: "hunai", name: "虎奶菌", latin: "Pleurotus tuber-regium", aliases: ["菌核侧耳", "虎奶菇"], category: "edible", season: "夏秋", seasons: ["夏", "秋"], habitat: "阔叶树腐木、土中菌核", habitats: ["腐木"], features: { capColor: "白", hymenium: "白色", hymeniumType: "菌褶", stem: "侧生", ring: false, volva: false, bruise: "不变", habitat: "腐木", seasons: ["夏", "秋"] }, description: "具大型菌核，菌盖浅褐至白色、漏斗状，菌褶白色下延。", caution: "食用菌，须彻底煮熟。以菌核为主要食用部位。", similar: ["与其它侧耳属区分。"], svg: { form: "agaric", capShape: "flat", cap: "#d8cfbc", cap2: "#b0a48c", texture: "smooth", stem: "#d8cfbc", gill: "#f2ecdc", bulbous: false } },

  /* ---------------------------- 慎食（新增） ---------------------------- */
  { id: "jituigu", name: "鸡腿菇", latin: "Coprinus comatus", aliases: ["毛头鬼伞", "鸡腿蘑"], category: "caution", season: "6—9 月", seasons: ["夏", "秋"], habitat: "草地、路边、粪肥地", habitats: ["草地"], features: { capColor: "白", hymenium: "白色后黑", hymeniumType: "菌褶", stem: "具菌环", ring: true, volva: false, bruise: "不变", habitat: "草地", seasons: ["夏", "秋"] }, description: "菌盖白色、长圆柱形，表面被鳞片，成熟后菌褶自溶成墨汁状。", caution: "慎食！与酒同食会引起双硫仑样反应（面部潮红、心慌等）；须在幼嫩时食用并彻底煮熟。", similar: ["与墨汁鬼伞等鬼伞类区分。"], svg: { form: "agaric", capShape: "bell", cap: "#f0eadc", cap2: "#d0c6b0", texture: "scaly", stem: "#efe9dc", gill: "#3a3a38", bulbous: false, ring: true } },
  { id: "kufenbao", name: "苦粉孢牛肝菌", latin: "Tylopilus felleus", aliases: ["苦牛肝", "苦菌"], category: "caution", season: "6—9 月", seasons: ["夏", "秋"], habitat: "针叶林、阔叶林地", habitats: ["林地"], features: { capColor: "褐", hymenium: "白色后粉", hymeniumType: "菌管", stem: "具网纹", ring: false, volva: false, bruise: "不变", habitat: "林地", seasons: ["夏", "秋"] }, description: "外形酷似美味牛肝菌，但味极苦；菌管白色后转粉红色。", caution: "不宜食用：味极苦，误食会引起肠胃不适。与美味牛肝菌极易混淆，务必区分（尝味极苦即弃）。", similar: ["与美味牛肝菌（可食）外形极相似，靠味苦鉴别。"], svg: { form: "bolete", capShape: "convex", cap: "#8a6644", cap2: "#684c30", texture: "smooth", stem: "#dcc8a8", gill: "#e8b8a8", bulbous: false } },
  { id: "hongjianshou", name: "红见手", latin: "Neoboletus magnificus", aliases: ["华丽新牛肝菌", "红牛肝菌"], category: "caution", season: "6—9 月", seasons: ["夏", "秋"], habitat: "松林、阔叶林地", habitats: ["林地"], features: { capColor: "红褐", hymenium: "黄色", hymeniumType: "菌管", stem: "粗壮", ring: false, volva: false, bruise: "变蓝", habitat: "林地", seasons: ["夏", "秋"] }, description: "菌盖红色至红褐色；菌管黄色；菌肉、菌管受伤后迅速变蓝。", caution: "慎食！属「见手青」类，必须切薄片、高温彻底烹熟，生食或未熟会中毒。", similar: ["与多种受伤变蓝的牛肝菌（见手青类）混淆，切勿自行采食。"], svg: { form: "bolete", capShape: "convex", cap: "#b04a38", cap2: "#843428", texture: "smooth", stem: "#d8c0a0", gill: "#e0b84e", bulbous: false, bruise: true } },
  { id: "baishenjun", name: "白参菌", latin: "Schizophyllum commune", aliases: ["裂褶菌", "白参"], category: "caution", season: "全年", seasons: ["春", "夏", "秋"], habitat: "阔叶树腐木", habitats: ["腐木"], features: { capColor: "白", hymenium: "裂褶状", hymeniumType: "菌褶", stem: "无柄、侧生", ring: false, volva: false, bruise: "不变", habitat: "腐木", seasons: ["春", "夏", "秋"] }, description: "子实体小、扇形，白色至灰褐色，菌褶自中心放射状裂开，干燥时卷曲。", caution: "部分人食用会过敏或肠胃不适；生食更易引起不适，务必彻底煮熟并少量尝试。", similar: ["与其它小型扇形菌区分。"], svg: { form: "agaric", capShape: "flat", cap: "#e8e2d4", cap2: "#c0b8a6", texture: "smooth", stem: "#e8e2d4", gill: "#c9c0ad", bulbous: false } },

  /* ---------------------------- 有毒 / 剧毒 ---------------------------- */
  {
    id: "zhiming-egao",
    name: "致命鹅膏",
    latin: "Amanita exitialis",
    aliases: ["白毒伞", "致命白毒伞"],
    category: "toxic",
    season: "6—9 月",
    seasons: ["夏", "秋"],
    habitat: "阔叶林、混交林地",
    habitats: ["林地"],
    features: {
      capColor: "白",
      hymenium: "白色",
      hymeniumType: "菌褶",
      stem: "具菌环、菌托",
      ring: true,
      volva: true,
      bruise: "不变",
      habitat: "林地",
      seasons: ["夏", "秋"]
    },
    description: "全株近白色：菌盖光滑、白色；菌褶白色；菌柄具膜质菌环，基部有杯状（袋状）菌托。",
    caution: "剧毒！含鹅膏肽类毒素，损害肝脏，可致急性肝衰竭甚至死亡，且毒素耐高温、无「银针变黑」等解毒说法。",
    similar: ["与可食的白色菌类（如草菇、白蚁菇等）极易混淆，是云南误食中毒的主要元凶之一。切勿采食白色伞菌！"],
    svg: { form: "agaric", capShape: "bell", cap: "#f3efe7", cap2: "#e4dccb", texture: "smooth", stem: "#f6f2ea", gill: "#f6f2ea", bulbous: true, ring: true, volva: true }
  },
  {
    id: "huihuawen-egao",
    name: "灰花纹鹅膏",
    latin: "Amanita fuliginea",
    aliases: ["灰鹅膏"],
    category: "toxic",
    season: "6—9 月",
    seasons: ["夏", "秋"],
    habitat: "阔叶林地",
    habitats: ["林地"],
    features: {
      capColor: "灰",
      hymenium: "白色",
      hymeniumType: "菌褶",
      stem: "具菌环、菌托",
      ring: true,
      volva: true,
      bruise: "不变",
      habitat: "林地",
      seasons: ["夏", "秋"]
    },
    description: "菌盖灰色、具纤维状花纹；菌褶白色；菌柄具菌环，基部有菌托。",
    caution: "剧毒！含鹅膏肽类毒素，可致肝损伤甚至死亡。切勿采食灰色、带菌环菌托的伞菌。",
    similar: ["与可食用的灰色菌类（如部分红菇）混淆风险高，务必注意菌环与菌托。"],
    svg: { form: "agaric", capShape: "bell", cap: "#9aa0a3", cap2: "#777d80", texture: "fibrillose", stem: "#e9e7e2", gill: "#f4f1ea", bulbous: true, ring: true, volva: true }
  },
  {
    id: "huanggai-egao",
    name: "黄盖鹅膏",
    latin: "Amanita subjunquillea",
    aliases: ["黄鹅膏"],
    category: "toxic",
    season: "7—9 月",
    seasons: ["夏", "秋"],
    habitat: "阔叶林地",
    habitats: ["林地"],
    features: {
      capColor: "黄",
      hymenium: "白色",
      hymeniumType: "菌褶",
      stem: "具菌环、菌托",
      ring: true,
      volva: true,
      bruise: "不变",
      habitat: "林地",
      seasons: ["夏", "秋"]
    },
    description: "菌盖黄色、常残留白色菌幕残片；菌褶白色；菌柄具菌环、基部有菌托。",
    caution: "剧毒！含鹅膏肽类毒素，可致急性肝损伤甚至死亡。",
    similar: ["与黄色系可食菌易混淆，关键看是否有菌环与菌托。"],
    svg: { form: "agaric", capShape: "bell", cap: "#e8c84e", cap2: "#c9a43a", texture: "spotted", stem: "#f0ead6", gill: "#f6f1e4", bulbous: true, ring: true, volva: true }
  },
  {
    id: "linbingbai-egao",
    name: "鳞柄白鹅膏",
    latin: "Amanita virosa",
    aliases: ["白鹅膏", "鳞柄白毒伞"],
    category: "toxic",
    season: "7—9 月",
    seasons: ["夏", "秋"],
    habitat: "针阔混交林地",
    habitats: ["林地"],
    features: {
      capColor: "白",
      hymenium: "白色",
      hymeniumType: "菌褶",
      stem: "具菌环、菌托、鳞片",
      ring: true,
      volva: true,
      bruise: "不变",
      habitat: "林地",
      seasons: ["夏", "秋"]
    },
    description: "全株白色，菌柄被细小鳞片，具菌环，基部有袋状菌托。",
    caution: "剧毒！含鹅膏肽类毒素，可致肝损伤甚至死亡。与可食白色菌类极易混淆。",
    similar: ["与多种白色可食菌（草菇、白蚁菇等）混淆，切勿采食带菌托的白色伞菌。"],
    svg: { form: "agaric", capShape: "bell", cap: "#f2eee4", cap2: "#e0d9c6", texture: "smooth", stem: "#f6f2ea", gill: "#f6f2ea", bulbous: true, ring: true, volva: true }
  },
  {
    id: "yaxizhe-honggu",
    name: "亚稀褶红菇",
    latin: "Russula subnigricans",
    aliases: ["亚稀褶黑菇", "火炭菌"],
    category: "toxic",
    season: "7—9 月",
    seasons: ["夏", "秋"],
    habitat: "阔叶林地",
    habitats: ["林地"],
    features: {
      capColor: "灰褐",
      hymenium: "白色至灰",
      hymeniumType: "菌褶",
      stem: "灰白色",
      ring: false,
      volva: false,
      bruise: "变红至黑",
      habitat: "林地",
      seasons: ["夏", "秋"]
    },
    description: "菌盖灰褐色、扁半球形；菌褶较稀疏、初白色后转灰；菌肉受伤后渐变红褐色至黑色。",
    caution: "剧毒！含横纹肌溶解毒素，可致急性肾功能衰竭甚至死亡。与可食用的稀褶红菇、密褶红菇极难区分，切勿采食不认识的灰褐色红菇。",
    similar: ["与可食的稀褶红菇、密褶红菇外形极相似，非专业人士切勿分辨。"],
    svg: { form: "agaric", capShape: "flat", cap: "#8a7a6a", cap2: "#6d5f52", texture: "smooth", stem: "#d9d2c6", gill: "#c9c2b6", bulbous: false }
  },
  {
    id: "duying-san",
    name: "毒蝇伞",
    latin: "Amanita muscaria",
    aliases: ["毒蝇鹅膏", "蛤蟆菌"],
    category: "toxic",
    season: "7—9 月",
    seasons: ["夏", "秋"],
    habitat: "针叶林、阔叶林地",
    habitats: ["林地"],
    features: {
      capColor: "红",
      hymenium: "白色",
      hymeniumType: "菌褶",
      stem: "具菌环、菌托",
      ring: true,
      volva: true,
      bruise: "不变",
      habitat: "林地",
      seasons: ["夏", "秋"]
    },
    description: "菌盖鲜红色、被白色鳞片/疣状突起；菌褶白色；菌柄具菌环，基部有菌托。",
    caution: "有毒！含蝇蕈碱等神经毒素，误食可引起幻觉、神经错乱、胃肠道症状等中毒表现。",
    similar: ["外形辨识度高，但仍勿因「鲜艳即有毒」而放松对白色/灰色剧毒菌的警惕。"],
    svg: { form: "agaric", capShape: "flat", cap: "#d3382c", cap2: "#a82519", texture: "spotted", stem: "#f2ece0", gill: "#f6f1e4", bulbous: true, ring: true, volva: true }
  },
  {
    id: "duhonggu",
    name: "毒红菇",
    latin: "Russula emetica",
    aliases: ["呕吐红菇"],
    category: "toxic",
    season: "6—9 月",
    seasons: ["夏", "秋"],
    habitat: "阔叶林地",
    habitats: ["林地"],
    features: {
      capColor: "红",
      hymenium: "白色",
      hymeniumType: "菌褶",
      stem: "白色",
      ring: false,
      volva: false,
      bruise: "不变",
      habitat: "林地",
      seasons: ["夏", "秋"]
    },
    description: "菌盖鲜红色、光滑；菌褶白色；菌柄白色。味极辛辣。",
    caution: "有毒！误食可引起剧烈呕吐、腹泻等胃肠炎型中毒。与可食的大红菇外形相似。",
    similar: ["大红菇（可食，味温和、菌褶后转黄）与毒红菇（味极辣、菌褶白色）极易混淆。"],
    svg: { form: "agaric", capShape: "flat", cap: "#d64541", cap2: "#a52f2c", texture: "smooth", stem: "#ece7da", gill: "#f6f1e4", bulbous: false }
  },
  {
    id: "daqingzhe-san",
    name: "大青褶伞",
    latin: "Chlorophyllum molybdites",
    aliases: ["铅绿褶菇", "绿褶菇"],
    category: "toxic",
    season: "5—10 月",
    seasons: ["春", "夏", "秋"],
    habitat: "草坪、路边草地",
    habitats: ["草地"],
    features: {
      capColor: "白",
      hymenium: "白色后变绿",
      hymeniumType: "菌褶",
      stem: "具菌环",
      ring: true,
      volva: false,
      bruise: "不变",
      habitat: "草地",
      seasons: ["春", "夏", "秋"]
    },
    description: "菌盖白色、中央具褐色鳞片；菌褶初白色后转灰绿色，孢子印绿色；菌柄有菌环；常见于草坪、路边。",
    caution: "有毒！是常见的胃肠炎型中毒原因。误食后恶心、呕吐、腹泻。",
    similar: ["与可食的高大环柄菇（菌褶白色、不变绿）易混淆，关键看菌褶是否变绿。"],
    svg: { form: "agaric", capShape: "flat", cap: "#efe9dc", cap2: "#8a6f52", texture: "scaly", stem: "#e9e2d2", gill: "#b8c4a6", bulbous: false, ring: true }
  },
  {
    id: "rouhe-linbing",
    name: "肉褐鳞环柄菇",
    latin: "Lepiota brunneoincarnata",
    aliases: ["肉褐鳞小伞"],
    category: "toxic",
    season: "7—10 月",
    seasons: ["夏", "秋"],
    habitat: "林地、草地",
    habitats: ["林地", "草地"],
    features: {
      capColor: "褐",
      hymenium: "白色",
      hymeniumType: "菌褶",
      stem: "具菌环",
      ring: true,
      volva: false,
      bruise: "不变",
      habitat: "林地",
      seasons: ["夏", "秋"]
    },
    description: "体型较小，菌盖褐色、被鳞片；菌褶白色；菌柄有菌环。",
    caution: "剧毒！含鹅膏肽类毒素，可致肝损伤甚至死亡。因个体较小，常被误采。",
    similar: ["与多种小型可食菇类易混淆，切勿采食不熟悉的小型伞菌。"],
    svg: { form: "agaric", capShape: "bell", cap: "#9a6a4a", cap2: "#7a4f34", texture: "scaly", stem: "#e2d8c6", gill: "#f4efe2", bulbous: false, ring: true }
  },

  /* ---------------------------- 有毒 / 剧毒（新增） ---------------------------- */
  { id: "baidu-egao", name: "白毒鹅膏", latin: "Amanita verna", aliases: ["白毒伞", "春生鹅膏"], category: "toxic", season: "5—9 月", seasons: ["春", "夏", "秋"], habitat: "阔叶林地", habitats: ["林地"], features: { capColor: "白", hymenium: "白色", hymeniumType: "菌褶", stem: "具菌环、菌托", ring: true, volva: true, bruise: "不变", habitat: "林地", seasons: ["春", "夏", "秋"] }, description: "全株白色，菌盖光滑、白色；菌褶白色；菌柄具菌环，基部有袋状菌托。", caution: "剧毒！含鹅膏肽类毒素，可致肝衰竭死亡。与可食白色菌类极易混淆。", similar: ["与草菇、白蚁菇等白色可食菌极易混淆，切勿采食带菌托的白色伞菌。"], svg: { form: "agaric", capShape: "bell", cap: "#f3efe7", cap2: "#e4dccb", texture: "smooth", stem: "#f6f2ea", gill: "#f6f2ea", bulbous: true, ring: true, volva: true } },
  { id: "jiaheyunban", name: "假褐云斑鹅膏", latin: "Amanita pseudoporphyria", aliases: ["假褐云斑鹅膏菌"], category: "toxic", season: "7—9 月", seasons: ["夏", "秋"], habitat: "针阔混交林地", habitats: ["林地"], features: { capColor: "灰褐", hymenium: "白色", hymeniumType: "菌褶", stem: "具菌环、菌托", ring: true, volva: true, bruise: "不变", habitat: "林地", seasons: ["夏", "秋"] }, description: "菌盖灰褐色、具纤维状云斑；菌褶白色；菌柄具菌环，基部有菌托。", caution: "有毒！含鹅膏类毒素，误食可致肝肾损伤。与灰褐色可食菌易混淆。", similar: ["与灰褐色红菇等可食菌区分，关键看菌环、菌托。"], svg: { form: "agaric", capShape: "bell", cap: "#8a8076", cap2: "#665e56", texture: "fibrillose", stem: "#e9e7e2", gill: "#f4f1ea", bulbous: true, ring: true, volva: true } },
  { id: "qiukuipao", name: "秋盔孢伞", latin: "Galerina marginata", aliases: ["纹缘盔孢伞", "秋生盔孢伞"], category: "toxic", season: "8—10 月", seasons: ["夏", "秋"], habitat: "腐木、枯枝上", habitats: ["腐木"], features: { capColor: "黄褐", hymenium: "褐色", hymeniumType: "菌褶", stem: "具菌环", ring: true, volva: false, bruise: "不变", habitat: "腐木", seasons: ["夏", "秋"] }, description: "小型、群生于腐木，菌盖黄褐色，菌褶褐色，菌柄有菌环。", caution: "剧毒！含鹅膏肽类毒素（与致命鹅膏同型），可致肝损伤死亡。切勿采食腐木上的小型褐菌。", similar: ["与可食的滑菇、榛蘑等腐木菌易混淆。"], svg: { form: "agaric", capShape: "convex", cap: "#b08a4e", cap2: "#826234", texture: "smooth", stem: "#d8c2a0", gill: "#8a6a44", bulbous: false, ring: true } },
  { id: "tiaogaikui", name: "条盖盔孢伞", latin: "Galerina sulciceps", aliases: ["沟条盔孢伞"], category: "toxic", season: "夏秋", seasons: ["夏", "秋"], habitat: "腐木、锯木屑上", habitats: ["腐木"], features: { capColor: "黄褐", hymenium: "褐色", hymeniumType: "菌褶", stem: "具菌环", ring: true, volva: false, bruise: "不变", habitat: "腐木", seasons: ["夏", "秋"] }, description: "小型、生于腐木/锯木屑，菌盖黄褐色、有放射状条纹，菌褶褐色，菌柄有菌环。", caution: "剧毒！含鹅膏肽类毒素，云南曾致多起中毒死亡事件。切勿采食腐木上的小型褐菌。", similar: ["与滑菇、榛蘑等腐木可食菌易混淆。"], svg: { form: "agaric", capShape: "convex", cap: "#a88444", cap2: "#7c6030", texture: "fibrillose", stem: "#d8c2a0", gill: "#8a6a44", bulbous: false, ring: true } },
  { id: "zheluhua", name: "赭鹿花菌", latin: "Gyromitra esculenta", aliases: ["鹿花菌", "假羊肚菌"], category: "toxic", season: "3—5 月", seasons: ["春"], habitat: "松林地", habitats: ["林地"], features: { capColor: "红褐", hymenium: "脑状回纹", hymeniumType: "脑状", stem: "白色、中空", ring: false, volva: false, bruise: "不变", habitat: "林地", seasons: ["春"] }, description: "菌盖红褐色、不规则脑状回纹（非蜂窝状）；菌柄白色、中空。", caution: "剧毒！含鹿花菌素（水解后生成单甲基肼），可致溶血、肝肾损伤甚至死亡。与羊肚菌易混淆。", similar: ["与羊肚菌（可食，蜂窝状凹坑）区分：鹿花菌菌盖为脑状回纹。"], svg: { form: "agaric", capShape: "convex", cap: "#9c4a30", cap2: "#6e3220", texture: "cracked", stem: "#ece5d5", gill: "#e2d6bf", bulbous: false } },
  { id: "daluhua", name: "大鹿花菌", latin: "Gyromitra gigas", aliases: ["鹿花菌", "大鹿花菌"], category: "toxic", season: "4—6 月", seasons: ["春", "夏"], habitat: "针叶林地", habitats: ["林地"], features: { capColor: "褐", hymenium: "脑状回纹", hymeniumType: "脑状", stem: "白色、中空", ring: false, volva: false, bruise: "不变", habitat: "林地", seasons: ["春", "夏"] }, description: "菌盖较大、浅褐至红褐色，脑状回纹；菌柄白色中空。", caution: "有毒！含鹿花菌素类毒素，误食可致溶血、肝肾损伤。与羊肚菌易混淆。", similar: ["与羊肚菌区分：菌盖脑状回纹而非蜂窝状。"], svg: { form: "agaric", capShape: "convex", cap: "#8a5a3e", cap2: "#5c3a28", texture: "cracked", stem: "#ece5d5", gill: "#e2d6bf", bulbous: false } },
  { id: "juanbian", name: "卷边网褶菌", latin: "Paxillus involutus", aliases: ["卷边桩菇", "卷缘网褶菌"], category: "toxic", season: "6—10 月", seasons: ["夏", "秋"], habitat: "针叶林、阔叶林地", habitats: ["林地"], features: { capColor: "褐", hymenium: "黄色下延", hymeniumType: "菌褶", stem: "与菌盖同色", ring: false, volva: false, bruise: "变褐", habitat: "林地", seasons: ["夏", "秋"] }, description: "菌盖黄褐色、边缘内卷；菌褶黄色下延、伤后变褐；菌柄与菌盖同色。", caution: "有毒！含致敏性毒素，反复食用可引发免疫性溶血，可致死。切勿采食。", similar: ["与部分可食牛肝菌、乳菇外形略似，注意区分。"], svg: { form: "agaric", capShape: "flat", cap: "#9c7848", cap2: "#74562f", texture: "smooth", stem: "#9c7848", gill: "#c9a060", bulbous: false } },
  { id: "baishuangbei", name: "白霜杯伞", latin: "Clitocybe dealbata", aliases: ["白霜杯蕈"], category: "toxic", season: "6—10 月", seasons: ["夏", "秋"], habitat: "草地、林地", habitats: ["草地", "林地"], features: { capColor: "白", hymenium: "白色", hymeniumType: "菌褶", stem: "白色", ring: false, volva: false, bruise: "不变", habitat: "草地", seasons: ["夏", "秋"] }, description: "小型，菌盖白色至浅灰、平展微凹；菌褶白色下延；菌柄白色。", caution: "有毒！含毒蕈碱，误食引起流涎、出汗、瞳孔缩小等中毒症状。与可食小白菌易混淆。", similar: ["与多种小型白色可食菌易混淆。"], svg: { form: "agaric", capShape: "flat", cap: "#f0eadc", cap2: "#d4ccb8", texture: "smooth", stem: "#efe9dc", gill: "#f6f1e4", bulbous: false } },
  { id: "xingbao", name: "星孢丝盖伞", latin: "Inocybe asterospora", aliases: ["星孢裂丝盖伞"], category: "toxic", season: "6—9 月", seasons: ["夏", "秋"], habitat: "阔叶林地", habitats: ["林地"], features: { capColor: "黄褐", hymenium: "灰褐", hymeniumType: "菌褶", stem: "褐色", ring: false, volva: false, bruise: "不变", habitat: "林地", seasons: ["夏", "秋"] }, description: "菌盖黄褐色、具放射状纤维；菌褶灰褐色；菌柄褐色、纤维质。", caution: "有毒！含毒蕈碱，误食引起流涎、出汗、心率减慢等。与可食菌易混淆。", similar: ["丝盖伞属多种有毒，与可食菌易混淆，需谨慎。"], svg: { form: "agaric", capShape: "conical", cap: "#a88444", cap2: "#7c6030", texture: "fibrillose", stem: "#a88444", gill: "#8a7a6a", bulbous: false } },
  { id: "liesigai", name: "裂丝盖伞", latin: "Inocybe rimosa", aliases: ["裂盖丝盖伞"], category: "toxic", season: "6—9 月", seasons: ["夏", "秋"], habitat: "阔叶林地", habitats: ["林地"], features: { capColor: "黄褐", hymenium: "灰褐", hymeniumType: "菌褶", stem: "褐色", ring: false, volva: false, bruise: "不变", habitat: "林地", seasons: ["夏", "秋"] }, description: "菌盖黄褐色、钟形，边缘常开裂；菌褶灰褐色；菌柄褐色。", caution: "有毒！含毒蕈碱，误食引起流涎、出汗、腹泻等中毒症状。", similar: ["与其它丝盖伞、可食菌区分。"], svg: { form: "agaric", capShape: "conical", cap: "#b08a4e", cap2: "#826234", texture: "fibrillose", stem: "#b08a4e", gill: "#8a7a6a", bulbous: false } },
  { id: "huangsigai", name: "黄丝盖伞", latin: "Inocybe fastigiata", aliases: ["黄丝膜菌"], category: "toxic", season: "6—9 月", seasons: ["夏", "秋"], habitat: "阔叶林地", habitats: ["林地"], features: { capColor: "黄", hymenium: "灰褐", hymeniumType: "菌褶", stem: "黄色", ring: false, volva: false, bruise: "不变", habitat: "林地", seasons: ["夏", "秋"] }, description: "菌盖黄色、钟形，具放射状纤维；菌褶灰褐色；菌柄黄色。", caution: "有毒！含毒蕈碱，误食引起流涎、出汗、胃肠炎等中毒症状。", similar: ["与其它黄色丝盖伞、可食菌区分。"], svg: { form: "agaric", capShape: "conical", cap: "#d8b04e", cap2: "#a88430", texture: "fibrillose", stem: "#d8b04e", gill: "#8a7a6a", bulbous: false } },
  { id: "zhehongkoumo", name: "赭红拟口蘑", latin: "Tricholomopsis rutilans", aliases: ["赭红口蘑"], category: "toxic", season: "6—9 月", seasons: ["夏", "秋"], habitat: "针叶林腐木", habitats: ["腐木"], features: { capColor: "红", hymenium: "黄色", hymeniumType: "菌褶", stem: "与菌盖同色", ring: false, volva: false, bruise: "不变", habitat: "腐木", seasons: ["夏", "秋"] }, description: "菌盖赭红色、被鳞片；菌褶黄色；菌柄与菌盖同色、被鳞片，常生于针叶树腐木。", caution: "有毒！误食引起恶心、呕吐、腹泻等胃肠炎型中毒。", similar: ["与其它红色菌区分。"], svg: { form: "agaric", capShape: "convex", cap: "#b04a38", cap2: "#843428", texture: "scaly", stem: "#b04a38", gill: "#e0c060", bulbous: false } },
  { id: "dianbing", name: "点柄臭黄菇", latin: "Russula senecis", aliases: ["臭黄菇", "点柄黄红菇"], category: "toxic", season: "6—9 月", seasons: ["夏", "秋"], habitat: "阔叶林地", habitats: ["林地"], features: { capColor: "黄褐", hymenium: "白色", hymeniumType: "菌褶", stem: "具褐色腺点", ring: false, volva: false, bruise: "不变", habitat: "林地", seasons: ["夏", "秋"] }, description: "菌盖黄褐色、具异味；菌褶白色；菌柄有褐色腺点。", caution: "有毒！误食引起呕吐、腹泻等胃肠炎型中毒。", similar: ["与可食红菇类区分。"], svg: { form: "agaric", capShape: "flat", cap: "#b8985a", cap2: "#8c7038", texture: "smooth", stem: "#d8c8a8", gill: "#f2e8d4", bulbous: false } },
  { id: "huangqunzhusun", name: "黄裙竹荪", latin: "Dictyophora multicolor", aliases: ["黄裙竹荪", "杂色竹荪"], category: "toxic", season: "6—9 月", seasons: ["夏", "秋"], habitat: "竹林、林地", habitats: ["林地"], features: { capColor: "黄（菌幕）", hymenium: "无典型菌褶", hymeniumType: "网状菌裙", stem: "黄色海绵质", ring: false, volva: false, bruise: "不变", habitat: "林地", seasons: ["夏", "秋"] }, description: "形态似竹荪，但菌裙（菌幕）为黄色，菌柄黄色海绵质，顶端菌盖有黏液。", caution: "有毒/不宜食用，误食可引起胃肠不适。与可食竹荪（白色菌裙）区分。", similar: ["与竹荪（白裙，可食）区分：黄裙竹荪菌裙黄色。"], svg: { form: "veiled", cap: "#e0c04e", cap2: "#6b5b3a", stem: "#e8d8a0", gill: "#e8d8a0" } },
  { id: "chenghuangmabo", name: "橙黄硬皮马勃", latin: "Scleroderma citrinum", aliases: ["硬皮马勃", "橙黄马勃"], category: "toxic", season: "6—9 月", seasons: ["夏", "秋"], habitat: "林地", habitats: ["林地"], features: { capColor: "黄褐", hymenium: "无典型菌褶（包被）", hymeniumType: "马勃", stem: "无柄", ring: false, volva: false, bruise: "不变", habitat: "林地", seasons: ["夏", "秋"] }, description: "子实体球形、无柄，外皮橙黄色、有疣状突起，内部成熟后紫黑色。", caution: "有毒！误食引起胃肠炎型中毒。与可食马勃（内部白色、松软）区分。", similar: ["与头状秃马勃等可食马勃区分：硬皮马勃外皮坚硬、内部色深。"], svg: { form: "agaric", capShape: "convex", cap: "#c99a4e", cap2: "#9c7430", texture: "cracked", stem: "#c99a4e", gill: "#8a6a44", bulbous: false } },
  { id: "dugou", name: "毒沟褶菌", latin: "Trogia venenata", aliases: ["小白菌", "毒沟褶伞"], category: "toxic", season: "6—9 月", seasons: ["夏", "秋"], habitat: "林地枯枝落叶", habitats: ["林地"], features: { capColor: "白", hymenium: "白色下延", hymeniumType: "菌褶", stem: "白色、细小", ring: false, volva: false, bruise: "不变", habitat: "林地", seasons: ["夏", "秋"] }, description: "小型、白色，菌盖平展微凹、边缘波状；菌褶白色下延；菌柄细小。", caution: "剧毒！曾引起云南「不明原因猝死」事件，含毒性成分，可致心脏骤停死亡。切勿采食不明小白菌。", similar: ["与多种小型白色可食菌极易混淆。"], svg: { form: "agaric", capShape: "flat", cap: "#f0eadc", cap2: "#d4ccb8", texture: "smooth", stem: "#efe9dc", gill: "#f6f1e4", bulbous: false } },
  { id: "helinbing", name: "褐鳞环柄菇", latin: "Lepiota helveola", aliases: ["褐鳞小伞"], category: "toxic", season: "7—10 月", seasons: ["夏", "秋"], habitat: "林地、草地", habitats: ["林地", "草地"], features: { capColor: "褐", hymenium: "白色", hymeniumType: "菌褶", stem: "具菌环", ring: true, volva: false, bruise: "不变", habitat: "林地", seasons: ["夏", "秋"] }, description: "小型，菌盖褐色、被鳞片；菌褶白色；菌柄有菌环。", caution: "剧毒！含鹅膏肽类毒素，可致肝损伤死亡。与小型可食菇易混淆。", similar: ["与肉褐鳞环柄菇等小型环柄菇混淆，切勿采食。"], svg: { form: "agaric", capShape: "bell", cap: "#8a5a3a", cap2: "#68422a", texture: "scaly", stem: "#e2d8c6", gill: "#f4efe2", bulbous: false, ring: true } },
  { id: "daduhua", name: "大毒滑锈伞", latin: "Hebeloma crustuliniforme", aliases: ["毒滑锈伞", "大毒粘滑菇"], category: "toxic", season: "8—11 月", seasons: ["夏", "秋"], habitat: "阔叶林地", habitats: ["林地"], features: { capColor: "白", hymenium: "灰褐", hymeniumType: "菌褶", stem: "白色", ring: false, volva: false, bruise: "不变", habitat: "林地", seasons: ["夏", "秋"] }, description: "菌盖白色至浅黄、粘滑；菌褶灰褐色；菌柄白色。", caution: "有毒！误食引起剧烈胃肠炎。与可食白菌易混淆。", similar: ["与多种白色可食菌区分。"], svg: { form: "agaric", capShape: "convex", cap: "#e8e2d4", cap2: "#c4bca8", texture: "smooth", stem: "#efe9dc", gill: "#9a8a76", bulbous: false } },
  { id: "tuhong", name: "土红鹅膏", latin: "Amanita rufoferruginea", aliases: ["土红粉盖鹅膏"], category: "toxic", season: "7—9 月", seasons: ["夏", "秋"], habitat: "针阔混交林地", habitats: ["林地"], features: { capColor: "红褐", hymenium: "白色", hymeniumType: "菌褶", stem: "具菌环、菌托", ring: true, volva: true, bruise: "不变", habitat: "林地", seasons: ["夏", "秋"] }, description: "菌盖土红色至红褐色、被粉末状鳞片；菌褶白色；菌柄具菌环、基部有菌托。", caution: "有毒！含鹅膏类毒素，误食可致肝肾损伤。", similar: ["与可食红菇等红色菌区分，关键看菌环、菌托。"], svg: { form: "agaric", capShape: "bell", cap: "#b06a4a", cap2: "#844a34", texture: "spotted", stem: "#e9e2d4", gill: "#f4f1ea", bulbous: true, ring: true, volva: true } },
  { id: "huangfenniu", name: "黄粉末牛肝菌", latin: "Pulveroboletus ravenelii", aliases: ["黄粉牛肝菌"], category: "toxic", season: "6—9 月", seasons: ["夏", "秋"], habitat: "阔叶林地", habitats: ["林地"], features: { capColor: "黄", hymenium: "黄色", hymeniumType: "菌管", stem: "黄色、具菌环", ring: true, volva: false, bruise: "变蓝", habitat: "林地", seasons: ["夏", "秋"] }, description: "菌盖黄色、被黄色粉末；菌管黄色；菌柄黄色、具菌环，受伤变蓝。", caution: "有毒！误食引起胃肠炎型中毒。与可食牛肝菌易混淆。", similar: ["与可食牛肝菌类区分。"], svg: { form: "bolete", capShape: "convex", cap: "#d8b04e", cap2: "#a88430", texture: "smooth", stem: "#d8b04e", gill: "#e0c060", bulbous: false, ring: true } },
  { id: "huangbanmogu", name: "黄斑蘑菇", latin: "Agaricus xanthodermus", aliases: ["黄斑伞菌"], category: "toxic", season: "6—10 月", seasons: ["夏", "秋"], habitat: "草地、林地", habitats: ["草地", "林地"], features: { capColor: "白", hymenium: "初粉后褐", hymeniumType: "菌褶", stem: "具菌环", ring: true, volva: false, bruise: "变黄", habitat: "草地", seasons: ["夏", "秋"] }, description: "菌盖白色、伤后变黄，有石炭酸味；菌褶初粉后褐；菌柄有菌环。", caution: "有毒！误食引起胃肠炎型中毒。与可食双孢蘑菇（白蘑菇）易混淆，靠伤后变黄+异味鉴别。", similar: ["与双孢蘑菇等白色蘑菇属区分：黄斑蘑菇伤后变黄、有异味。"], svg: { form: "agaric", capShape: "convex", cap: "#f0eadc", cap2: "#d4ccb8", texture: "smooth", stem: "#efe9dc", gill: "#b08a78", bulbous: false, ring: true } },
  { id: "dufenzhe", name: "毒粉褶菌", latin: "Entoloma sinuatum", aliases: ["毒粉褶蕈", "毒赤褶菇"], category: "toxic", season: "7—9 月", seasons: ["夏", "秋"], habitat: "阔叶林地", habitats: ["林地"], features: { capColor: "白", hymenium: "初白后粉", hymeniumType: "菌褶", stem: "白色", ring: false, volva: false, bruise: "不变", habitat: "林地", seasons: ["夏", "秋"] }, description: "大型，菌盖白色至浅灰、边缘内卷；菌褶初白色后转粉红色；菌柄白色。", caution: "有毒！误食引起剧烈胃肠炎。与可食白色大菌易混淆。", similar: ["与多种白色可食菌区分。"], svg: { form: "agaric", capShape: "convex", cap: "#ece6d8", cap2: "#c4bcac", texture: "smooth", stem: "#efe9dc", gill: "#c99a9a", bulbous: false } },
  { id: "xiaodouhonggu", name: "小毒红菇", latin: "Russula fragilis", aliases: ["脆红菇", "小毒红菇"], category: "toxic", season: "6—9 月", seasons: ["夏", "秋"], habitat: "阔叶林地", habitats: ["林地"], features: { capColor: "红", hymenium: "白色", hymeniumType: "菌褶", stem: "白色", ring: false, volva: false, bruise: "不变", habitat: "林地", seasons: ["夏", "秋"] }, description: "小型，菌盖红色、薄而脆，边缘常开裂；菌褶白色；菌柄白色。", caution: "有毒！味辛辣，误食引起胃肠炎型中毒。与可食红菇类易混淆。", similar: ["与毒红菇、大红菇等红色红菇区分。"], svg: { form: "agaric", capShape: "flat", cap: "#c04440", cap2: "#90302c", texture: "smooth", stem: "#ece7da", gill: "#f6f1e4", bulbous: false } },
  { id: "cushenghuang", name: "簇生黄韧伞", latin: "Hypholoma fasciculare", aliases: ["簇生沿丝伞", "毒韧黑伞"], category: "toxic", season: "6—10 月", seasons: ["夏", "秋"], habitat: "腐木、树桩", habitats: ["腐木"], features: { capColor: "黄", hymenium: "黄绿后黑", hymeniumType: "菌褶", stem: "黄色", ring: false, volva: false, bruise: "不变", habitat: "腐木", seasons: ["夏", "秋"] }, description: "簇生于腐木/树桩，菌盖黄色、中央褐；菌褶黄绿色后转黑；菌柄黄色。", caution: "有毒！味苦，误食引起胃肠炎型中毒。与可食腐木菌易混淆。", similar: ["与滑菇、榛蘑等腐木可食菌区分。"], svg: { form: "agaric", capShape: "convex", cap: "#d8b04e", cap2: "#a88430", texture: "smooth", stem: "#d8b04e", gill: "#9a9a5a", bulbous: false } },
  { id: "huazhesan", name: "斑褶伞", latin: "Panaeolus papilionaceus", aliases: ["花褶伞", "斑褶菇"], category: "toxic", season: "6—9 月", seasons: ["夏", "秋"], habitat: "草地、粪肥地", habitats: ["草地"], features: { capColor: "灰褐", hymenium: "灰黑", hymeniumType: "菌褶", stem: "褐色、细长", ring: false, volva: false, bruise: "不变", habitat: "草地", seasons: ["夏", "秋"] }, description: "小型，菌盖钟形、灰褐色；菌褶灰黑色、有斑驳；菌柄细长。", caution: "有毒/致幻！含致幻成分，误食可引起幻觉、精神异常。与可食小菌易混淆。", similar: ["斑褶伞属多种含毒，与可食小型菌区分。"], svg: { form: "agaric", capShape: "bell", cap: "#8a7a6a", cap2: "#665c52", texture: "smooth", stem: "#9a8a7a", gill: "#5a5a56", bulbous: false } },
  { id: "moniugan", name: "魔牛肝菌", latin: "Boletus satanas", aliases: ["撒旦牛肝菌", "毒牛肝菌"], category: "toxic", season: "7—9 月", seasons: ["夏", "秋"], habitat: "阔叶林地", habitats: ["林地"], features: { capColor: "白", hymenium: "红色", hymeniumType: "菌管", stem: "粗壮、红色", ring: false, volva: false, bruise: "变蓝", habitat: "林地", seasons: ["夏", "秋"] }, description: "菌盖灰白色、半球形；菌管红色；菌柄粗壮、红色具网纹，受伤变蓝。", caution: "有毒！生食或未熟食会引起剧烈胃肠炎，须谨慎。切勿采食。", similar: ["与可食牛肝菌类区分（菌管红色是其显著特征）。"], svg: { form: "bolete", capShape: "convex", cap: "#d8cfc0", cap2: "#b0a694", texture: "smooth", stem: "#c04438", gill: "#d0483c", bulbous: false } },
  { id: "hongwangniu", name: "红网牛肝菌", latin: "Boletus luridus", aliases: ["褐黄牛肝菌", "红网柄牛肝菌"], category: "toxic", season: "6—9 月", seasons: ["夏", "秋"], habitat: "阔叶林地", habitats: ["林地"], features: { capColor: "褐", hymenium: "黄色", hymeniumType: "菌管", stem: "红色网纹", ring: false, volva: false, bruise: "变蓝", habitat: "林地", seasons: ["夏", "秋"] }, description: "菌盖褐色、半球形；菌管黄色；菌柄具红色网纹，受伤变蓝。", caution: "有毒！生食或未熟食可引起胃肠炎等中毒，须经彻底加工（传统上云南部分地区食用，但风险高，不建议）。", similar: ["与可食牛肝菌类区分。"], svg: { form: "bolete", capShape: "convex", cap: "#8a6244", cap2: "#68482e", texture: "smooth", stem: "#d8b8a0", gill: "#e0c060", bulbous: false, bruise: true } },
  { id: "heluhua", name: "褐鹿花菌", latin: "Gyromitra infula", aliases: ["马鞍菌", "鹿花菌近缘种"], category: "toxic", season: "7—9 月", seasons: ["夏", "秋"], habitat: "针叶林腐木", habitats: ["腐木"], features: { capColor: "褐", hymenium: "马鞍状", hymeniumType: "脑状", stem: "白色", ring: false, volva: false, bruise: "不变", habitat: "腐木", seasons: ["夏", "秋"] }, description: "菌盖马鞍形、红褐至深褐色，脑状回纹；菌柄白色。", caution: "有毒！含鹿花菌素类毒素，误食可致溶血、肝肾损伤。", similar: ["与可食羊肚菌、马鞍菌属区分。"], svg: { form: "agaric", capShape: "convex", cap: "#8a5234", cap2: "#5e3822", texture: "cracked", stem: "#ece5d5", gill: "#e2d6bf", bulbous: false } },
  { id: "bianhei", name: "变黑蜡伞", latin: "Hygrocybe conica", aliases: ["变黑湿伞", "圆锥蜡伞"], category: "toxic", season: "6—9 月", seasons: ["夏", "秋"], habitat: "草地、林地", habitats: ["草地", "林地"], features: { capColor: "橙", hymenium: "黄色", hymeniumType: "菌褶", stem: "黄色", ring: false, volva: false, bruise: "变黑", habitat: "草地", seasons: ["夏", "秋"] }, description: "小型，菌盖橙黄至红色、圆锥形；菌褶黄色；全株受伤或老熟后变黑。", caution: "有毒！误食引起胃肠不适。与可食蜡伞类区分。", similar: ["与可食蜡伞区分：变黑蜡伞伤后变黑。"], svg: { form: "agaric", capShape: "conical", cap: "#d8883a", cap2: "#b0662a", texture: "smooth", stem: "#d8a048", gill: "#e0c060", bulbous: false } },
  { id: "duhuojun", name: "毒火菇", latin: "Podostroma cornu-damae", aliases: ["红角肉棒菌", "火焰茸"], category: "toxic", season: "6—9 月", seasons: ["夏", "秋"], habitat: "阔叶林地", habitats: ["林地"], features: { capColor: "红", hymenium: "无典型菌褶（棒状）", hymeniumType: "棒状", stem: "红色、棒状分枝", ring: false, volva: false, bruise: "不变", habitat: "林地", seasons: ["夏", "秋"] }, description: "子实体珊瑚状或指状分枝，鲜红色至橙红色，形似火焰。", caution: "剧毒！含单端孢霉烯类毒素，误食可致多器官衰竭、白细胞减少甚至死亡。切勿接触采食。", similar: ["与可食珊瑚菌类（扫把菌）区分：毒火菇鲜红色。"], svg: { form: "coral", cap: "#c03028", cap2: "#8a1f18", stem: "#c03028", gill: "#c03028" } }
];
